### ISSUE TITLE
bookmarks bar and folders have disappeared in Chrome

### ISSUE THREAD

**Issue by loren229** [xbrowsersync/app#115]
**Describe the issue you are experiencing**
Started chrome for the first time since the new version of xBrowserSync came out. First few minutes everything was normal with my bookmark bar and folders the way they were. But when I tried to add a new bookmark using the Chrome star, suddenly all my folders disappeared, and I got error messages that I didn't understand (see below). The new bookmarks wouldn't stay bookmarked either, they disappeared. As far as I can tell, all my old bookmarks are still there I think, but xBrowserSync won't show me the folders. 

**How can the issue be reproduced?**
NA

**Screenshots**
![image](https://user-images.githubusercontent.com/53648653/62410738-b94b1580-b62d-11e9-8e9c-1f72a22f1156.png)
![image](https://user-images.githubusercontent.com/53648653/62410744-d253c680-b62d-11e9-998b-478ef488838e.png)
![image](https://user-images.githubusercontent.com/53648653/62410751-e7305a00-b62d-11e9-8948-da8a5c6533b9.png)

**Desktop browser**
Please complete the following information for all affected desktop browsers:

 - OS: Windows 10
 - Browser: Chrome
 - Version: v1.5.0

**Mobile device**
Please complete the following information for all affected mobile devices:
NA

**Application log**
Please include the logs from the affected clients:

<details>
<summary>Log entries</summary>

```
2019-08-03 09:36:31.579	[trace]	Upgrading from 1.4.0 to 1.5.0
2019-08-03 09:36:31.614	[trace]	Starting up
2019-08-03 09:36:31.796	[trace]	{"displayHelp":false,"displayOtherSyncsWarning":true,"displayUpdated":true,"lastUpdated":"2018-10-12T23:28:55.324Z","syncEnabled":true,"syncId":"9db9d981143c43efb0ab3929421c1c1a","appVersion":"1.5.0","platform":{"name":"chrome","version":"74.0.3729","mobile":false,"os":"Windows 10"}}
2019-08-03 10:01:25.025	[trace]	onCreated event detected
2019-08-03 10:01:25.102	[trace]	Sync 2mwe42 (push) queued (1 waiting to sync)
2019-08-03 10:01:25.141	[trace]	Sync 2mwe42 failed.
2019-08-03 10:01:25.153	[error]	bookmarks.sync: [10110] LocalBookmarkNotFound
2019-08-03 10:01:25.161	[trace]	Sync plk28w (pull) queued (1 waiting to sync)
2019-08-03 10:01:27.468	[trace]	Local population completed in 0.048s
2019-08-03 10:01:27.485	[trace]	Sync plk28w completed (0 waiting to sync)
2019-08-03 10:01:27.507	[trace]	Local sync data refreshed
2019-08-03 10:01:29.199	[trace]	onMoved event detected
2019-08-03 10:01:29.242	[trace]	Sync m7o8i1 (push) queued (1 waiting to sync)
2019-08-03 10:01:29.252	[trace]	Sync m7o8i1 failed.
2019-08-03 10:01:29.268	[error]	bookmarks.sync: [10110] LocalBookmarkNotFound
2019-08-03 10:01:29.276	[trace]	Sync 5nepnx (pull) queued (1 waiting to sync)
2019-08-03 10:01:30.797	[trace]	Local population completed in 0.016s
2019-08-03 10:01:30.822	[trace]	Sync 5nepnx completed (0 waiting to sync)
2019-08-03 10:01:30.840	[trace]	Local sync data refreshed
2019-08-03 10:01:33.254	[trace]	onCreated event detected
2019-08-03 10:01:33.321	[trace]	Sync 19jopny (push) queued (1 waiting to sync)
2019-08-03 10:01:34.850	[trace]	Encryption failed.
2019-08-03 10:01:34.872	[trace]	Sync 19jopny failed.
2019-08-03 10:01:34.886	[error]	bookmarks.sync: [10109] InvalidCredentials	Error: Invalid string. Length must be a multiple of 4 at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:375:1195) at Object.h [as toByteArray] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:375:1449) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:1667:36 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:154:326 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:52:3
2019-08-03 10:02:04.944	[trace]	Updates available, local:2019-08-03T10:01:34.875Z remote:2018-10-12T23:28:55.324Z
2019-08-03 10:02:10.941	[trace]	Sync 1phs5tp (pull) queued (1 waiting to sync)
2019-08-03 10:02:12.497	[trace]	Local population completed in 0.013s
2019-08-03 10:02:12.514	[trace]	Sync 1phs5tp completed (0 waiting to sync)
2019-08-03 10:02:15.455	[trace]	onCreated event detected
2019-08-03 10:02:15.505	[trace]	Sync 176qodl (push) queued (1 waiting to sync)
2019-08-03 10:02:17.120	[trace]	Encryption failed.
2019-08-03 10:02:17.134	[trace]	Sync 176qodl failed.
2019-08-03 10:02:17.149	[error]	bookmarks.sync: [10109] InvalidCredentials	Error: Invalid string. Length must be a multiple of 4 at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:375:1195) at Object.h [as toByteArray] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:375:1449) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:1667:36 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:154:326 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:52:3
2019-08-03 10:02:46.160	[trace]	Updates available, local:2019-08-03T10:02:17.142Z remote:2018-10-12T23:28:55.324Z
2019-08-03 10:03:21.039	[trace]	Sync 15s9hlw (pull) queued (1 waiting to sync)
2019-08-03 10:03:22.645	[trace]	Local population completed in 0.011s
2019-08-03 10:03:22.661	[trace]	Sync 15s9hlw completed (0 waiting to sync)
2019-08-03 10:03:32.675	[trace]	onCreated event detected
2019-08-03 10:03:32.712	[trace]	Sync 1acm4z9 (push) queued (1 waiting to sync)
2019-08-03 10:03:34.193	[trace]	Encryption failed.
2019-08-03 10:03:34.207	[trace]	Sync 1acm4z9 failed.
2019-08-03 10:03:34.220	[error]	bookmarks.sync: [10109] InvalidCredentials	Error: Invalid string. Length must be a multiple of 4 at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:375:1195) at Object.h [as toByteArray] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:375:1449) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:1667:36 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:154:326 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:52:3
2019-08-03 10:03:51.690	[trace]	Updates available, local:2019-08-03T10:03:34.212Z remote:2018-10-12T23:28:55.324Z
2019-08-03 10:04:01.777	[trace]	Toolbar sync disabled
2019-08-03 10:05:10.970	[trace]	onCreated event detected
2019-08-03 10:05:11.031	[trace]	Sync 8iiqen (push) queued (1 waiting to sync)
2019-08-03 10:05:11.046	[warn]	Unable to get metadata: Cannot access a chrome:// URL
2019-08-03 10:05:12.445	[trace]	Local data out of sync, local:2019-08-03T10:03:34.212Z remote:2018-10-12T23:28:55.324Z
2019-08-03 10:05:12.468	[trace]	Sync 8iiqen failed.
2019-08-03 10:05:12.480	[error]	bookmarks.sync: [10114] DataOutOfSync
2019-08-03 10:05:12.494	[trace]	Sync gd4cbm (pull) queued (1 waiting to sync)
2019-08-03 10:05:13.303	[trace]	Not clearing toolbar
2019-08-03 10:05:13.334	[trace]	Not populating toolbar
2019-08-03 10:05:13.346	[trace]	Local population completed in 0.028s
2019-08-03 10:05:13.358	[trace]	Sync gd4cbm completed (0 waiting to sync)
2019-08-03 10:05:13.366	[trace]	Local sync data refreshed
2019-08-03 10:05:50.667	[trace]	onCreated event detected
2019-08-03 10:05:50.720	[trace]	Sync 1dab2bv (push) queued (1 waiting to sync)
2019-08-03 10:05:52.244	[trace]	Encryption failed.
2019-08-03 10:05:52.251	[trace]	Sync 1dab2bv failed.
2019-08-03 10:05:52.261	[error]	bookmarks.sync: [10109] InvalidCredentials	Error: Invalid string. Length must be a multiple of 4 at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:375:1195) at Object.h [as toByteArray] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:375:1449) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:1667:36 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:154:326 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:52:3
2019-08-03 10:06:00.602	[trace]	onCreated event detected
2019-08-03 10:06:00.646	[trace]	Sync l60p10 (push) queued (1 waiting to sync)
2019-08-03 10:06:02.017	[trace]	Local data out of sync, local:2019-08-03T10:05:52.257Z remote:2018-10-12T23:28:55.324Z
2019-08-03 10:06:02.047	[trace]	Sync l60p10 failed.
2019-08-03 10:06:02.063	[error]	bookmarks.sync: [10114] DataOutOfSync
2019-08-03 10:06:02.089	[trace]	Sync 1989e3p (pull) queued (1 waiting to sync)
2019-08-03 10:06:03.132	[trace]	Not clearing toolbar
2019-08-03 10:06:03.144	[trace]	Not populating toolbar
2019-08-03 10:06:03.154	[trace]	Local population completed in 0.011s
2019-08-03 10:06:03.172	[trace]	Sync 1989e3p completed (0 waiting to sync)
2019-08-03 10:06:03.191	[trace]	Local sync data refreshed
2019-08-03 10:06:35.595	[trace]	Starting up
2019-08-03 10:06:35.675	[trace]	{"displayHelp":false,"displayOtherSyncsWarning":true,"displayUpdated":false,"lastUpdated":"2018-10-12T23:28:55.324Z","networkDisconnected":false,"syncBookmarksToolbar":false,"syncEnabled":true,"syncId":"9db9d981143c43efb0ab3929421c1c1a","appVersion":"1.5.0","platform":{"name":"chrome","version":"75.0.3770","mobile":false,"os":"Windows 10"}}
2019-08-03 10:08:36.171	[trace]	onCreated event detected
2019-08-03 10:08:36.203	[trace]	Sync wjx2ci (push) queued (1 waiting to sync)
2019-08-03 10:08:38.412	[trace]	Encryption failed.
2019-08-03 10:08:38.426	[trace]	Sync wjx2ci failed.
2019-08-03 10:08:38.438	[error]	bookmarks.sync: [10109] InvalidCredentials	Error: Invalid string. Length must be a multiple of 4 at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:375:1195) at Object.h [as toByteArray] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:375:1449) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:1667:36 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:154:326 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:52:3
2019-08-03 10:09:01.155	[trace]	onCreated event detected
2019-08-03 10:09:01.195	[trace]	Sync 1sqqr8k (push) queued (1 waiting to sync)
2019-08-03 10:09:02.909	[trace]	Local data out of sync, local:2019-08-03T10:08:38.431Z remote:2018-10-12T23:28:55.324Z
2019-08-03 10:09:02.923	[trace]	Sync 1sqqr8k failed.
2019-08-03 10:09:02.939	[error]	bookmarks.sync: [10114] DataOutOfSync
2019-08-03 10:09:02.947	[trace]	Sync 1ctxzdc (pull) queued (1 waiting to sync)
2019-08-03 10:09:04.424	[trace]	Not clearing toolbar
2019-08-03 10:09:04.432	[trace]	Not populating toolbar
2019-08-03 10:09:04.443	[trace]	Local population completed in 0.008s
2019-08-03 10:09:04.457	[trace]	Sync 1ctxzdc completed (0 waiting to sync)
2019-08-03 10:09:04.469	[trace]	Local sync data refreshed
2019-08-03 10:15:40.300	[trace]	Toolbar sync enabled
2019-08-03 10:15:40.323	[trace]	Sync 2n0dtv (pull) queued (1 waiting to sync)
2019-08-03 10:15:41.976	[trace]	Local population completed in 0.008s
2019-08-03 10:15:41.992	[trace]	Sync 2n0dtv completed (0 waiting to sync)
2019-08-03 10:24:28.026	[trace]	onCreated event detected
2019-08-03 10:24:28.070	[trace]	Sync 1jl4366 (push) queued (1 waiting to sync)
2019-08-03 10:24:29.532	[trace]	Encryption failed.
2019-08-03 10:24:29.551	[trace]	Sync 1jl4366 failed.
2019-08-03 10:24:29.564	[error]	bookmarks.sync: [10109] InvalidCredentials	Error: Invalid string. Length must be a multiple of 4 at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:375:1195) at Object.h [as toByteArray] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:375:1449) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:1667:36 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:154:326 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:52:3
2019-08-03 10:24:45.265	[trace]	onCreated event detected
2019-08-03 10:24:45.310	[trace]	Sync 15usxbd (push) queued (1 waiting to sync)
2019-08-03 10:24:46.722	[trace]	Local data out of sync, local:2019-08-03T10:24:29.557Z remote:2018-10-12T23:28:55.324Z
2019-08-03 10:24:46.749	[trace]	Sync 15usxbd failed.
2019-08-03 10:24:46.777	[error]	bookmarks.sync: [10114] DataOutOfSync
2019-08-03 10:24:46.802	[trace]	Sync 1puixf2 (pull) queued (1 waiting to sync)
2019-08-03 10:24:47.825	[trace]	Local population completed in 0.009s
2019-08-03 10:24:47.846	[trace]	Sync 1puixf2 completed (0 waiting to sync)
2019-08-03 10:24:47.865	[trace]	Local sync data refreshed
2019-08-03 10:31:33.552	[trace]	onCreated event detected
2019-08-03 10:31:33.579	[trace]	Sync c2hjoh (push) queued (1 waiting to sync)
2019-08-03 10:31:35.887	[trace]	Encryption failed.
2019-08-03 10:31:35.894	[trace]	Sync c2hjoh failed.
2019-08-03 10:31:35.905	[error]	bookmarks.sync: [10109] InvalidCredentials	Error: Invalid string. Length must be a multiple of 4 at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:375:1195) at Object.h [as toByteArray] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:375:1449) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:1667:36 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:154:326 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:52:3
2019-08-03 10:32:49.467	[trace]	onCreated event detected
2019-08-03 10:32:49.512	[trace]	Sync 1vwoviy (push) queued (1 waiting to sync)
2019-08-03 10:32:50.902	[trace]	Local data out of sync, local:2019-08-03T10:31:35.900Z remote:2018-10-12T23:28:55.324Z
2019-08-03 10:32:50.923	[trace]	Sync 1vwoviy failed.
2019-08-03 10:32:50.943	[error]	bookmarks.sync: [10114] DataOutOfSync
2019-08-03 10:32:50.957	[trace]	Sync newmrk (pull) queued (1 waiting to sync)
2019-08-03 10:32:52.238	[trace]	Local population completed in 0.007s
2019-08-03 10:32:52.260	[trace]	Sync newmrk completed (0 waiting to sync)
2019-08-03 10:32:52.273	[trace]	Local sync data refreshed
```
</details>

**Comment by nero120** [comment]
Hi @loren229, yes your sync still exists on [api.xbrowsersync.org](https://api.xbrowsersync.org/), first of all let's try and sort the encryption error. Are you only syncing to the browser stated above? Next, can you please follow these steps:

1. Clear the log by going to the Settings panel and clicking the Clear Log button in the Issues section.
2. Disable the sync by clicking Disable Sync in the Settings panel > Sync section
3. Re-enable the sync by entering your password and clicking Sync.
4. Use the xBrowserSync pop up to add a bookmark.
5. Use the browser's bookmark functionality to add a bookmark.

If you have any issues please reply and paste the application log.

**Comment by loren229** [comment]
Yeah that doesn't sound right. :( I'm sure I've added more in Chrome since then
And I tried the first two steps, but then can't find my password, so I guess I've lost all my bookmarks anyway :(

Thanks anyway :(

**Comment by nero120** [comment]
I'm really sorry to hear that @loren229 😭 

Did you take a backup previously? If so you can restore from the backup. Alternatively, are the bookmarks still present locally? If so you can create a new sync, you'll lose the descriptions and tags but at least you'll have the bookmarks themselves.

**Comment by loren229** [comment]
I can't find a backup of them, no. And they're not still present locally, that was my issue to start with, that all my folders on my bookmarks bar had disappeared. 

Thank you for your time.

**Comment by nero120** [comment]
I'm truly sorry about that @loren229, I absolutely need to get auto-backups implemented asap.

It's a small hope but you can try to sync with as many password guesses as you can remember, it doesn't lock you out of anything.
