### ISSUE TITLE
Unable to move multiple bookmarks into sibling folders

### ISSUE THREAD

**Issue by jcrben** [xbrowsersync/app#158]
**Describe the issue you are experiencing**
When I drag multiple bookmarks over into a new folder in Google Chrome, an error throws.

**How can the issue be reproduced?**
1. Go to the Google Chrome Bookmarks Manager 
2. Click on a bookmark folder: "Bookmarks bar->dev->interviewing"
3. Select more than one bookmark using Shift+Click and drag them into "Bookmarks bar->dev->interviewing->company-prospects"
4. Redirected from folder to main Bookmarks Manager window, an error pops up which I cannot read completely (see screenshot)

Note: one other browser is connected to the sync, running Firefox on Manjaro Linux. However, I can reproduce this while that computer is turned off.

Note also: this doesn't happen if I move a single bookmark at a time.

**Screenshots**
If applicable, add screenshots to help explain your problem:
![image](https://user-images.githubusercontent.com/5614134/73691337-03698e00-4687-11ea-9722-2485bcde258f.png)

**Desktop browser**
Please complete the following information for all affected desktop browsers:

 - OS: macOS 10.14.5 (18F132)
 - Browser Version 79.0.3945.130 (Official Build) (64-bit)
 - Version 1.5.0

**Application log**
Please include the logs from the affected clients:

<details>
<summary>Log entries</summary>

```
2020-02-03 21:15:39.927	[trace]	onMoved event detected
2020-02-03 21:15:40.059	[trace]	onMoved event detected
2020-02-03 21:15:40.258	[trace]	onMoved event detected
2020-02-03 21:15:40.387	[trace]	onMoved event detected
2020-02-03 21:15:40.485	[trace]	Sync 1b3vydf (push) queued (1 waiting to sync)
2020-02-03 21:15:40.534	[trace]	Sync 1r3a2i6 (push) queued (1 waiting to sync)
2020-02-03 21:15:40.538	[trace]	Sync 1pa8vho (push) queued (2 waiting to sync)
2020-02-03 21:15:40.546	[trace]	Sync pu4lo8 (push) queued (3 waiting to sync)
2020-02-03 21:15:41.542	[trace]	Sync 1b3vydf failed.
2020-02-03 21:15:41.552	[error]	bookmarks.sync: [10111] XBookmarkNotFound	TypeError: Cannot read property 'splice' of undefined at Object.addNewInXBookmarks [as AddNewInXBookmarks] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2393:29) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3608:65 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:154:326 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:52:3
2020-02-03 21:15:41.558	[trace]	Sync q946x1 (pull) queued (1 waiting to sync)
2020-02-03 21:15:43.195	[trace]	Local population completed in 0.86s
2020-02-03 21:15:43.213	[trace]	Sync q946x1 completed (0 waiting to sync)
2020-02-03 21:15:43.223	[trace]	Local sync data refreshed```
</details>

**Comment by nero120** [comment]
Hi @jcrben, I've recently fixed a number of bugs when moving bookmarks, would you be willing to try the latest beta and see if it resolves your issue? I'd be very grateful!

https://github.com/xbrowsersync/app/releases/tag/v1.5.1beta2

In Chrome, you'll need to enable Developer Mode in `chrome://extensions/`, then you should be able to drag the zip file to install the update. If you also want to install on Firefox, just drag the xpi file onto `about:addons`.

**Comment by jcrben** [comment]
It says:
![image](https://user-images.githubusercontent.com/5614134/73694036-2185bd00-468c-11ea-9e25-8a58c30ff5ac.png)

Error looks similar:
<details>

```md
2020-02-03 21:50:15.188	[trace]	onMoved event detected
2020-02-03 21:50:15.340	[trace]	onMoved event detected
2020-02-03 21:50:15.440	[trace]	onMoved event detected
2020-02-03 21:50:15.683	[trace]	Sync 1hmq60c (push) queued (1 waiting to sync)
2020-02-03 21:50:15.702	[trace]	Sync c69s01 (push) queued (2 waiting to sync)
2020-02-03 21:50:15.750	[trace]	Sync qnmceh (push) queued (3 waiting to sync)
2020-02-03 21:50:16.200	[trace]	Processing sync 1hmq60c
2020-02-03 21:50:16.246	[trace]	Sync 1hmq60c failed.
2020-02-03 21:50:16.258	[error]	bookmarks.sync: [10111] XBookmarkNotFound	TypeError: Cannot read property 'splice' of undefined at Object.addNewInXBookmarks [as AddNewInXBookmarks] (chrome-extension://ddgpbbmhffilglcejldhmligekoldnoi/js/background.min.js:2486:29) at chrome-extension://ddgpbbmhffilglcejldhmligekoldnoi/js/background.min.js:3734:65 at chrome-extension://ddgpbbmhffilglcejldhmligekoldnoi/js/background.min.js:140:44 at m.$digest (chrome-extension://ddgpbbmhffilglcejldhmligekoldnoi/js/background.min.js:151:185) at chrome-extension://ddgpbbmhffilglcejldhmligekoldnoi/js/background.min.js:154:326 at Tg.completeTask (chrome-extension://ddgpbbmhffilglcejldhmligekoldnoi/js/background.min.js:166:15) at chrome-extension://ddgpbbmhffilglcejldhmligekoldnoi/js/background.min.js:52:3
2020-02-03 21:50:16.266	[trace]	Sync 19stwn7 (pull) queued (1 waiting to sync)
2020-02-03 21:50:16.270	[trace]	Processing sync 19stwn7
2020-02-03 21:50:17.601	[trace]	Local population completed in 0.665s
2020-02-03 21:50:17.613	[trace]	Sync 19stwn7 committed (0 waiting to sync)
2020-02-03 21:50:17.623	[trace]	Local sync data refreshed
```
</details>

**Comment by nero120** [comment]
Ok thanks for trying @jcrben, I've replicated the error and will sort out a fix.

**Comment by nero120** [comment]
Uploaded a new [beta](https://github.com/xbrowsersync/app/releases/tag/v1.5.1beta) with the fix, give it a try if you have a moment.

**Comment by nero120** [comment]
@jcrben it has become clear that there is more complexity to fixing the existing bugs when moving bookmarks, so I've backed out the changes I made in order to not delay the current release any further. I have re-opened this issue and will hope to resolve this complex issue once the current release is out.

**Comment by DreClark** [comment]
I am having a similar issue when I try to move subfolders of bookmarks into a different subfolder, all of my changes refresh back to the original layout. This occurs in Chrome, Firefox, Brave and Edge (I know these two aren't officially supported yet).

**Comment by nero120** [comment]
@DreClark this issue has now been fixed and will be included in the upcoming release.

**Comment by xocox** [comment]
Hello, just to mention this bug also affect Windows Chrome extension, thanks for your work
