### ISSUE TITLE
android version doesn't support choose of user's own service providers.

### ISSUE THREAD

**Issue by xinminglai** [xbrowsersync/app#175]
**Describe the issue you are experiencing**

On android app, when I try to change the service to my own servers, I got error in red text, which is "Unable to connect to the service", I'm sure the server works for desktop browsers in both firefox and chrome. And only when I try to use that server address in android, I got the error. But it works when I try to connect to other service provided on the official site though.

**How can the issue be reproduced?**

1. When we enter the app, in the "scan your sync ID" screen, tap the top-right gear icon.
2. In Service section, click "Change Service" button.
3. Type your private server

**Screenshots**

![Screenshot_20200405-233105](https://user-images.githubusercontent.com/625040/78502837-ad53bc80-7795-11ea-801c-6e435cc96ed8.jpg)

**Mobile device**
Please complete the following information for all affected mobile devices:

 - Device: MiPad4 Plus
 - OS: Android 10 (Bliss ROM for mipad 4) [https://forum.xda-developers.com/mi-pad-4/development/rom-blissroms-v12-2-t4038271]
 - Version 1.5.1

**Application log**
Please include the logs from the affected clients:

<details>
<summary>Log entries</summary>
2020-04-05 15:21:18.929	[trace]	Installed v1.5.1
2020-04-05 15:21:18.944	[trace]	Starting up
2020-04-05 15:21:18.974	[trace]	{"appVersion":"1.5.1","displayHelp":true,"platform":{"name":"Android","device":"Xiaomi MI PAD 4 PLUS"}}
2020-04-05 15:21:40.588	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2386:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onabort (file:///android_asset/www/js/app.min.js:112:301) at N (file:///android_asset/www/js/app.min.js:111:146) at file:///android_asset/www/js/app.min.js:113:58 at Tg.completeTask (file:///android_asset/www/js/app.min.js:166:15)
2020-04-05 15:21:42.297	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2386:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onabort (file:///android_asset/www/js/app.min.js:112:301) at N (file:///android_asset/www/js/app.min.js:111:146) at file:///android_asset/www/js/app.min.js:113:58 at Tg.completeTask (file:///android_asset/www/js/app.min.js:166:15)
2020-04-05 15:21:46.353	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2386:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onabort (file:///android_asset/www/js/app.min.js:112:301) at N (file:///android_asset/www/js/app.min.js:111:146) at file:///android_asset/www/js/app.min.js:113:58 at Tg.completeTask (file:///android_asset/www/js/app.min.js:166:15)
2020-04-05 15:22:01.250	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2386:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
</details>

**Comment by nero120** [comment]
@xinminglai you're using a local IP range (192.168...) which is why it works locally when your connect using the desktop xBrowserSync extension. To connect via your Android device you need to use the public IP address of the machine it's running and ensure that any incoming public requests are routed correctly.

**Comment by xinminglai** [comment]
Hi, @nero120 
I also tried to use ssh-tunnel to create reverse port map to map the server to the public ip,
Still can't connect to that public ip with right port. And I open the url in browser, It works fine.

**Comment by nero120** [comment]
Can you post the public address of the service please so I can check it?
