### ISSUE TITLE
Bookmarks "delete" is auto-reverted and failed to sync in Opera browser

### ISSUE THREAD

**Issue by zhenkas** [xbrowsersync/app#223]
**Describe the issue you are experiencing**
I am trying to setup a sync between Opera and Chrome. 
Opera browser supports Chrome extension, and looks like it is working except this issue.
Bookmarks "delete" is auto-reverted and failed to sync in Opera browser.
Bookmarks "add" works as expected.
**How can the issue be reproduced?**

Sync bookmarks from Opera to Chrome.
Make bookmark change in Chrome (add some new bookmark to bookmask bar).
Sync from Chrome to Opera once.
After this you will unable to delete bookmarks in Opera, it will be auto-reverted, and "failed to sync" popup
Note: adding new bookmarks in Opera works well, also deleting bookmarks in Chrome works.

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Desktop browser**
Please complete the following information for all affected desktop browsers:

 - OS: Win10
 - Browser Opera
 - Version 69.0.3686.77

**Application log**
2020-08-02 08:06:53.386	[trace]	Installed v1.5.2
2020-08-02 08:06:53.402	[trace]	Starting up
2020-08-02 08:06:53.428	[trace]	{"checkForAppUpdates":true,"displayHelp":true,"displayPermissions":true,"syncBookmarksToolbar":true,"appVersion":"1.5.2","platform":{"name":"opera","version":"69.0.3686","mobile":false,"os":"Windows 10"}}
2020-08-02 08:07:56.032	[trace]	Sync q38wno (push) queued
2020-08-02 08:07:56.037	[trace]	Processing sync q38wno (0 in queue)
2020-08-02 08:07:56.138	[trace]	Sync enabled
2020-08-02 08:07:56.475	[trace]	Remote bookmarks data updated at 2020-08-02T08:07:57.248Z
2020-08-02 08:07:56.484	[trace]	New sync id created: 343680fe0cd24c4f91ff113b89aedcf6
2020-08-02 08:09:40.389	[trace]	Sync disabled
2020-08-02 08:10:41.540	[trace]	Sync 1h0zsl3 (pull) queued
2020-08-02 08:10:41.545	[trace]	Processing sync 1h0zsl3 (0 in queue)
2020-08-02 08:10:42.553	[trace]	Local population completed in 0.488s
2020-08-02 08:10:42.564	[trace]	Sync enabled
2020-08-02 08:10:42.576	[trace]	Synced to existing id: e6b244fdf746419696ac2296aa240043
2020-08-02 08:14:08.776	[trace]	onCreated event detected
2020-08-02 08:14:09.788	[trace]	Sync krl22j (push) queued
2020-08-02 08:14:09.885	[trace]	Processing sync krl22j (0 in queue)
2020-08-02 08:14:10.178	[trace]	Remote bookmarks data updated at 2020-08-02T08:14:10.959Z
2020-08-02 08:16:25.766	[trace]	Updates available, local:2020-08-02T08:14:10.959Z remote:2020-08-02T08:16:17.972Z
2020-08-02 08:16:31.274	[trace]	Sync 1gk74dx (pull) queued
2020-08-02 08:16:31.284	[trace]	Processing sync 1gk74dx (0 in queue)
2020-08-02 08:16:32.245	[trace]	Local population completed in 0.567s
2020-08-02 08:17:04.134	[trace]	onCreated event detected
2020-08-02 08:17:05.149	[trace]	Sync 7613k4 (push) queued
2020-08-02 08:17:05.240	[trace]	Processing sync 7613k4 (0 in queue)
2020-08-02 08:17:05.534	[error]		Error: [10114] DataOutOfSync at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2439:42 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at m.$apply (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:155:35) at k (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:106:129) at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:111:206) at XMLHttpRequest.y.onload (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:112:125)
2020-08-02 08:17:05.540	[trace]	Sync k9e5tt (pull) queued
2020-08-02 08:17:05.544	[trace]	Processing sync k9e5tt (0 in queue)
2020-08-02 08:17:06.418	[trace]	Local population completed in 0.497s
2020-08-02 08:17:06.433	[trace]	Local sync data refreshed
2020-08-02 08:17:24.966	[trace]	onCreated event detected
2020-08-02 08:17:25.983	[trace]	Sync cxrxy2 (push) queued
2020-08-02 08:17:26.071	[trace]	Processing sync cxrxy2 (0 in queue)
2020-08-02 08:17:26.363	[trace]	Remote bookmarks data updated at 2020-08-02T08:17:27.142Z
2020-08-02 08:17:57.608	[trace]	onMoved event detected
2020-08-02 08:17:58.631	[trace]	Sync ep6hq6 (push) queued
2020-08-02 08:17:58.715	[trace]	Sync ep6hq6 failed
2020-08-02 08:17:58.723	[error]	bookmarks.sync: [10110] LocalBookmarkNotFound
2020-08-02 08:17:58.731	[trace]	Sync 1s9g3pt (pull) queued
2020-08-02 08:17:58.737	[trace]	Processing sync 1s9g3pt (0 in queue)
2020-08-02 08:17:59.736	[trace]	Local population completed in 0.54s
2020-08-02 08:17:59.753	[trace]	Local sync data refreshed
2020-08-02 08:18:06.969	[trace]	onMoved event detected
2020-08-02 08:18:08.000	[trace]	Sync jbjcow (push) queued
2020-08-02 08:18:08.105	[trace]	Sync jbjcow failed
2020-08-02 08:18:08.115	[error]	bookmarks.sync: [10110] LocalBookmarkNotFound
2020-08-02 08:18:08.124	[trace]	Sync 10j9jzc (pull) queued
2020-08-02 08:18:08.128	[trace]	Processing sync 10j9jzc (0 in queue)
2020-08-02 08:18:09.088	[trace]	Local population completed in 0.496s
2020-08-02 08:18:09.102	[trace]	Local sync data refreshed
2020-08-02 08:18:17.861	[trace]	Sync disabled
2020-08-02 08:18:48.248	[trace]	Sync w97tux (pull) queued
2020-08-02 08:18:48.253	[trace]	Processing sync w97tux (0 in queue)
2020-08-02 08:18:49.320	[trace]	Local population completed in 0.575s
2020-08-02 08:18:49.331	[trace]	Sync enabled
2020-08-02 08:18:49.344	[trace]	Synced to existing id: e6b244fdf746419696ac2296aa240043
2020-08-02 08:20:03.544	[trace]	onMoved event detected
2020-08-02 08:20:04.590	[trace]	Sync mo1xyc (push) queued
2020-08-02 08:20:04.682	[trace]	Sync mo1xyc failed
2020-08-02 08:20:04.692	[error]	bookmarks.sync: [10110] LocalBookmarkNotFound
2020-08-02 08:20:04.707	[trace]	Sync lqfb0l (pull) queued
2020-08-02 08:20:04.716	[trace]	Processing sync lqfb0l (0 in queue)
2020-08-02 08:20:05.801	[trace]	Local population completed in 0.596s
2020-08-02 08:20:05.817	[trace]	Local sync data refreshed
2020-08-02 08:29:17.346	[trace]	Updates available, local:2020-08-02T08:19:36.566Z remote:2020-08-02T08:29:12.364Z
2020-08-02 08:29:18.807	[trace]	Sync 12w7eh9 (pull) queued
2020-08-02 08:29:18.812	[trace]	Processing sync 12w7eh9 (0 in queue)
2020-08-02 08:29:19.719	[trace]	Local population completed in 0.576s
2020-08-02 08:29:24.752	[trace]	onMoved event detected
2020-08-02 08:29:25.815	[trace]	Sync 19ecl7w (push) queued
2020-08-02 08:29:25.930	[trace]	Sync 19ecl7w failed
2020-08-02 08:29:25.939	[error]	bookmarks.sync: [10110] LocalBookmarkNotFound
2020-08-02 08:29:25.946	[trace]	Sync 1et8mfw (pull) queued
2020-08-02 08:29:25.950	[trace]	Processing sync 1et8mfw (0 in queue)
2020-08-02 08:29:26.778	[trace]	Local population completed in 0.497s
2020-08-02 08:29:26.793	[trace]	Local sync data refreshed
2020-08-02 08:29:36.003	[trace]	onMoved event detected
2020-08-02 08:29:37.060	[trace]	Sync a8wy57 (push) queued
2020-08-02 08:29:37.195	[trace]	Sync a8wy57 failed
2020-08-02 08:29:37.206	[error]	bookmarks.sync: [10110] LocalBookmarkNotFound
2020-08-02 08:29:37.214	[trace]	Sync 1k03h05 (pull) queued
2020-08-02 08:29:37.219	[trace]	Processing sync 1k03h05 (0 in queue)
2020-08-02 08:29:38.115	[trace]	Local population completed in 0.557s
2020-08-02 08:29:38.131	[trace]	Local sync data refreshed
2020-08-02 08:31:16.246	[trace]	onMoved event detected
2020-08-02 08:31:17.315	[trace]	Sync w6216b (push) queued
2020-08-02 08:31:17.451	[trace]	Sync w6216b failed
2020-08-02 08:31:17.463	[error]	bookmarks.sync: [10110] LocalBookmarkNotFound
2020-08-02 08:31:17.473	[trace]	Sync 11gipaz (pull) queued
2020-08-02 08:31:17.479	[trace]	Processing sync 11gipaz (0 in queue)
2020-08-02 08:31:18.420	[trace]	Local population completed in 0.563s
2020-08-02 08:31:18.438	[trace]	Local sync data refreshed
2020-08-02 08:34:12.785	[trace]	onMoved event detected
2020-08-02 08:34:13.861	[trace]	Sync ch2aze (push) queued
2020-08-02 08:34:14.006	[trace]	Sync ch2aze failed
2020-08-02 08:34:14.016	[error]	bookmarks.sync: [10110] LocalBookmarkNotFound
2020-08-02 08:34:14.024	[trace]	Sync ug2eg0 (pull) queued
2020-08-02 08:34:14.028	[trace]	Processing sync ug2eg0 (0 in queue)
2020-08-02 08:34:14.972	[trace]	Local population completed in 0.575s
2020-08-02 08:34:14.986	[trace]	Local sync data refreshed
2020-08-02 08:34:29.945	[trace]	onCreated event detected
2020-08-02 08:34:30.988	[trace]	Sync srs0ac (push) queued
2020-08-02 08:34:31.186	[trace]	Processing sync srs0ac (0 in queue)
2020-08-02 08:34:31.530	[trace]	Remote bookmarks data updated at 2020-08-02T08:34:32.371Z
2020-08-02 08:34:41.957	[trace]	onCreated event detected
2020-08-02 08:34:43.005	[trace]	Sync azawc8 (push) queued
2020-08-02 08:34:43.192	[trace]	Processing sync azawc8 (0 in queue)
2020-08-02 08:34:43.973	[trace]	Remote bookmarks data updated at 2020-08-02T08:34:44.682Z
<details>
<summary>Any change to bookmarks auto-reverted, and failed to sync</summary>

```
Download the Application log from the Settings panel and paste the contents here.
```
</details>

**Comment by nero120** [comment]
Opera is not currently supported, follow [this issue](https://github.com/xbrowsersync/app/issues/11) to be notified about updates.
