### ISSUE TITLE
Android cannot connect to local LAN server

### ISSUE THREAD

**Issue by peerobo** [xbrowsersync/app#234]
**Describe the issue you are experiencing**
A clear and concise description of your issue:

I have a local ubuntu server in the LAN, running xbrowsersync service at ip 192.168.1.6. Desktop of xbrowsersync running in chrome on Windows PC can connect to the service but Android version on my phone cannot.

**Screenshots**
If applicable, add screenshots to help explain your problem:

![image](https://user-images.githubusercontent.com/4023681/92198372-64b44280-ee9e-11ea-8027-a59d3ad9da57.png)
![Screenshot_2020-09-04-11-06-17-93](https://user-images.githubusercontent.com/4023681/92198545-d7bdb900-ee9e-11ea-946c-ca07f0eed7ce.jpg)

**Desktop browser**
Please complete the following information for all affected desktop browsers:

 - OS: Win 10, MacOS
 - Browser MS Edge

**Mobile device**
Please complete the following information for all affected mobile devices:

 - Device: Oppo Find X2 Pro
 - OS: Android 10
 - Version XBrowserSync 1.5.2

**Application log**
Please include the logs from the affected clients:

<details>
<summary>Log entries</summary>

```
2020-09-04 03:36:50.978	[trace]	Installed v1.5.2
2020-09-04 03:36:50.988	[trace]	Starting up
2020-09-04 03:36:50.994	[trace]	{"checkForAppUpdates":true,"appVersion":"1.5.2","displayHelp":true,"platform":{"name":"Android","device":"OPPO PDEM30"}}
2020-09-04 03:37:16.322	[trace]	Scanned: a3b5e5b5c92745b987b7d89dbf61226f|$$|http://192.168.1.6:8080
2020-09-04 03:37:17.351	[trace]	Service url changed to: http://192.168.1.6:8080
2020-09-04 03:37:17.383	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:37:17.450	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:37:24.375	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:37:28.627	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:37:33.874	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:37:46.061	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:42:29.686	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:42:36.204	[trace]	Starting up
2020-09-04 03:42:36.217	[trace]	{"appVersion":"1.5.2","checkForAppUpdates":true,"serviceUrl":"http://192.168.1.6:8080","displayHelp":false,"syncId":"a3b5e5b5c92745b987b7d89dbf61226f","platform":{"name":"Android","device":"OPPO PDEM30"}}
2020-09-04 03:42:36.322	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:42:36.398	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:42:51.889	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:42:56.786	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:43:06.354	[trace]	Scanned: a3b5e5b5c92745b987b7d89dbf61226f|$$|http://192.168.1.6:8080
2020-09-04 03:43:07.391	[trace]	Service url changed to: http://192.168.1.6:8080
2020-09-04 03:43:07.425	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:43:07.501	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:43:14.859	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:43:17.339	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:44:46.689	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:44:53.764	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:45:05.937	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:56:45.794	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:56:50.567	[trace]	Starting up
2020-09-04 03:56:50.578	[trace]	{"appVersion":"1.5.2","checkForAppUpdates":true,"serviceUrl":"http://192.168.1.6:8080","displayHelp":false,"syncId":"a3b5e5b5c92745b987b7d89dbf61226f","platform":{"name":"Android","device":"OPPO PDEM30"}}
2020-09-04 03:56:50.690	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:56:50.762	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:56:53.604	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2020-09-04 03:56:54.387	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
```
</details>

**Comment by peerobo** [comment]
I've already tried using host name instead of IP address, still the same error.

**Comment by nero120** [comment]
Confirmed, will be fixed for the next release. Thanks @peerobo!

**Comment by youknow16** [comment]
Version 1.6.0.932 still has this problem.

**Comment by youknow16** [comment]
I see many pre-releases being made.
Can you include this patch in one of them?
This problem prevents me from using the server at all! I think it's very urgent!

**Comment by youknow16** [comment]
I just tried it with 1.6.0.941 and it worked!
I had previously tried it with 1.6.0.935 and it wasn't working!!

**Comment by nero120** [comment]
@youknow16 ok glad to hear it! Please bear in mind these are pre-releases so are not yet ready for full release which means you may encounter other issues. Make sure to take regular back ups of your data!

**Comment by youknow16** [comment]
Thanks.
This probably needs another post but is there a way to make automatic backups of the database itself? I installed the server using docker.

**Comment by nero120** [comment]
Yes absolutely, can you open an issue in the [api-docker](https://github.com/xbrowsersync/api-docker) repo and ask the question there? I'll post the answer and that way others that have the same question can find it also.

**Comment by youknow16** [comment]
`You got it! Thanks`
