### ISSUE TITLE
Local change fail to save in Vivaldi

### ISSUE THREAD

**Issue by JJKW1984** [xbrowsersync/app#281]
**Describe the issue you are experiencing**
When using Vivaldi making any changes to any bookmark results in the "Sync Error Local data has been refreshed, please redo previous unsynced changes."

**How can the issue be reproduced?**

1. Go to Vivaldi Bookmark Bar
2. RIght click and select edit
3. Edit the name and select save
4. After it save, the entire bar is resync and you See error

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Desktop browser**
- OS: Windows 

Vivaldi | 3.6.2165.36 (Stable channel) (64-bit)
-- | --
Revision | bcf357a77b2f4450fd626b1bd424ecce4df171d3
OS | Windows 10 OS Version 2009 (Build 19042.789)
JavaScript | V8 8.8.278.15
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.151 Safari/537.36
Command Line | "C:\Users\josep\AppData\Local\Vivaldi\Application\vivaldi.exe" --flag-switches-begin --flag-switches-end --origin-trial-disabled-features=SecurePaymentConfirmation --save-page-as-mhtml
Executable Path | C:\Users\josep\AppData\Local\Vivaldi\Application\vivaldi.exe
Profile Path | C:\Users\josep\AppData\Local\Vivaldi\User Data\Default

<summary>Log entries</summary>

2021-02-08 22:58:59.273	[trace]	Installed v1.5.2
2021-02-08 22:58:59.295	[trace]	Starting up
2021-02-08 22:58:59.326	[trace]	{"checkForAppUpdates":true,"displayHelp":true,"displayPermissions":true,"syncBookmarksToolbar":true,"appVersion":"1.5.2","platform":{"name":"chrome","version":"88.0.4324","mobile":false,"os":"Windows 10"}}
2021-02-08 23:02:33.275	[trace]	Optional permissions granted
2021-02-08 23:03:43.408	[trace]	Sync ljtlsr (pull) queued
2021-02-08 23:03:43.413	[trace]	Processing sync ljtlsr (0 in queue)
2021-02-08 23:03:43.902	[trace]	Local population completed in 0.185s
2021-02-08 23:03:43.920	[trace]	Sync enabled
2021-02-08 23:03:43.936	[trace]	Synced to existing id: c05f83d2fd9648c5971463238a2e4d18
2021-02-08 23:06:21.498	[trace]	onMoved event detected
2021-02-08 23:06:22.526	[trace]	Sync 19ad359 (push) queued
2021-02-08 23:06:22.627	[trace]	Sync 19ad359 failed
2021-02-08 23:06:22.636	[error]	bookmarks.sync: [10110] LocalBookmarkNotFound
2021-02-08 23:06:22.646	[trace]	Sync 1j6mg2 (pull) queued
2021-02-08 23:06:22.652	[trace]	Processing sync 1j6mg2 (0 in queue)
2021-02-08 23:06:23.125	[trace]	Local population completed in 0.203s
2021-02-08 23:06:23.146	[trace]	Local sync data refreshed
2021-02-08 23:06:24.447	[trace]	onMoved event detected
2021-02-08 23:06:25.484	[trace]	Sync lgwsoi (push) queued
2021-02-08 23:06:25.569	[trace]	Sync lgwsoi failed
2021-02-08 23:06:25.583	[error]	bookmarks.sync: [10110] LocalBookmarkNotFound
2021-02-08 23:06:25.592	[trace]	Sync 6j3cd0 (pull) queued
2021-02-08 23:06:25.596	[trace]	Processing sync 6j3cd0 (0 in queue)
2021-02-08 23:06:26.071	[trace]	Local population completed in 0.196s
2021-02-08 23:06:26.093	[trace]	Local sync data refreshed
2021-02-08 23:07:04.608	[trace]	onMoved event detected
2021-02-08 23:07:05.643	[trace]	Sync 1lv4g6h (push) queued
2021-02-08 23:07:05.734	[trace]	Sync 1lv4g6h failed
2021-02-08 23:07:05.745	[error]	bookmarks.sync: [10110] LocalBookmarkNotFound
2021-02-08 23:07:05.756	[trace]	Sync dn9f86 (pull) queued
2021-02-08 23:07:05.758	[trace]	Processing sync dn9f86 (0 in queue)
2021-02-08 23:07:05.963	[trace]	onMoved event detected
2021-02-08 23:07:06.292	[trace]	Local population completed in 0.222s
2021-02-08 23:07:06.315	[trace]	Local sync data refreshed
2021-02-08 23:07:07.014	[trace]	Sync 1kkb8aj (push) queued
2021-02-08 23:07:07.118	[trace]	Sync 1kkb8aj failed
2021-02-08 23:07:07.129	[error]	bookmarks.sync: [10110] LocalBookmarkNotFound
2021-02-08 23:07:07.140	[trace]	Sync oyemtm (pull) queued
2021-02-08 23:07:07.144	[trace]	Processing sync oyemtm (0 in queue)
2021-02-08 23:07:07.668	[trace]	Local population completed in 0.249s
2021-02-08 23:07:07.690	[trace]	Local sync data refreshed
2021-02-08 23:07:08.749	[trace]	onMoved event detected
2021-02-08 23:07:09.822	[trace]	Sync 1iam04w (push) queued
2021-02-08 23:07:09.930	[trace]	Sync 1iam04w failed
2021-02-08 23:07:09.940	[error]	bookmarks.sync: [10110] LocalBookmarkNotFound
2021-02-08 23:07:09.951	[trace]	Sync xamqod (pull) queued
2021-02-08 23:07:09.955	[trace]	Processing sync xamqod (0 in queue)
2021-02-08 23:07:10.463	[trace]	Local population completed in 0.212s
2021-02-08 23:07:10.485	[trace]	Local sync data refreshed
2021-02-08 23:07:15.891	[trace]	onMoved event detected
2021-02-08 23:07:16.955	[trace]	Sync 9s4yse (push) queued
2021-02-08 23:07:17.069	[trace]	Sync 9s4yse failed
2021-02-08 23:07:17.079	[error]	bookmarks.sync: [10110] LocalBookmarkNotFound
2021-02-08 23:07:17.090	[trace]	Sync 1cxlblf (pull) queued
2021-02-08 23:07:17.094	[trace]	Processing sync 1cxlblf (0 in queue)
2021-02-08 23:07:17.643	[trace]	Local population completed in 0.214s
2021-02-08 23:07:17.667	[trace]	Local sync data refreshed
2021-02-08 23:07:27.733	[trace]	onMoved event detected
2021-02-08 23:07:28.807	[trace]	Sync 19drsvk (push) queued
2021-02-08 23:07:28.963	[trace]	Sync 19drsvk failed
2021-02-08 23:07:28.976	[error]	bookmarks.sync: [10110] LocalBookmarkNotFound
2021-02-08 23:07:28.992	[trace]	Sync 1koa5pu (pull) queued
2021-02-08 23:07:28.996	[trace]	Processing sync 1koa5pu (0 in queue)
2021-02-08 23:07:29.568	[trace]	Local population completed in 0.226s
2021-02-08 23:07:29.592	[trace]	Local sync data refreshed
2021-02-08 23:07:34.616	[trace]	onCreated event detected
2021-02-08 23:07:35.664	[trace]	Sync 1vs41rk (push) queued
2021-02-08 23:07:35.815	[trace]	Processing sync 1vs41rk (0 in queue)
2021-02-08 23:07:36.142	[trace]	Remote bookmarks data updated at 2021-02-08T23:07:38.275Z
2021-02-08 23:08:26.387	[trace]	onCreated event detected
2021-02-08 23:08:27.458	[trace]	Sync 1tztwj2 (push) queued
2021-02-08 23:08:27.672	[trace]	Processing sync 1tztwj2 (0 in queue)
2021-02-08 23:08:28.019	[trace]	Remote bookmarks data updated at 2021-02-08T23:08:30.154Z
2021-02-08 23:08:36.570	[trace]	onCreated event detected
2021-02-08 23:08:37.626	[trace]	Sync 1ko4nk1 (push) queued
2021-02-08 23:08:37.833	[trace]	Processing sync 1ko4nk1 (0 in queue)
2021-02-08 23:08:37.878	[trace]	Sync 1ko4nk1 failed
2021-02-08 23:08:37.885	[error]	bookmarks.sync: [10111] XBookmarkNotFound	TypeError: Cannot read property 'splice' of undefined at Object.addNewInXBookmarks [as AddNewInXBookmarks] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2563:29) at Object.bookmarksCreated [as Created] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3844:26) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3555:55 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:154:326 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:52:3
2021-02-08 23:08:37.892	[trace]	{"bookmark":{"bookmarkbar":false,"dateAdded":1612825716556,"description":"A new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team","index":2,"nickname":"","parentId":"6","partner":"","speeddial":false,"thumbnail":"","title":"Notion – The all-in-one workspace for your notes, tasks, wikis, and databases.","trash":false,"url":"https://www.notion.so/oauth2callback?state=eyJjYWxsYmFja1R5cGUiOiJwb3B1cCIsImVuY3J5cHRlZFRva2VuIjoiY2QwZWJmYWQ2YTMwYzI4NmUwMzdkOTdlMTA0ZGU4MmU4YjYzMjdkYjMzY2NiYzJiZjM4OTg2ODE5NzM4ODcwM2U5YmRhYzNmOGMyOTViZTM1MDRiMjJjODY0OGI3YzNjZGJmMmQxZTM4NTY4ODY3M2JiYjU5MGI1NTNlZjY5NDhjYzcwNzk3MWMwODQzZDYwZjdmZGMwOTA5NWZlIn0%3D&code=4%2F0AY0e-g6X_ZxjFYbvdv9zA32-uvWFCb2RBY8QKN0tJOB8CZ2RW_nm8DPEQvEmgWTneO0jMw&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&prompt=none#","tags":null},"container":"[xbs] Toolbar","indexPath":[1,2],"type":1}
2021-02-08 23:08:37.900	[trace]	Sync b4etuu (pull) queued
2021-02-08 23:08:37.905	[trace]	Processing sync b4etuu (0 in queue)
2021-02-08 23:08:38.464	[trace]	Local population completed in 0.266s
2021-02-08 23:08:38.487	[trace]	Local sync data refreshed
2021-02-08 23:13:12.908	[trace]	onMoved event detected
2021-02-08 23:13:14.003	[trace]	Sync vh5agf (push) queued
2021-02-08 23:13:14.159	[trace]	Sync vh5agf failed
2021-02-08 23:13:14.171	[error]	bookmarks.sync: [10110] LocalBookmarkNotFound
2021-02-08 23:13:14.181	[trace]	Sync 1slnuk9 (pull) queued
2021-02-08 23:13:14.185	[trace]	Processing sync 1slnuk9 (0 in queue)
2021-02-08 23:13:14.983	[trace]	Local population completed in 0.221s
2021-02-08 23:13:15.004	[trace]	Local sync data refreshed
2021-02-08 23:14:13.872	[trace]	onChanged event detected
2021-02-08 23:14:14.877	[trace]	Sync 1318thq (push) queued
2021-02-08 23:14:15.114	[trace]	Processing sync 1318thq (0 in queue)
2021-02-08 23:14:15.128	[trace]	Sync 1318thq failed
2021-02-08 23:14:15.143	[error]	bookmarks.sync: [10111] XBookmarkNotFound	Error at Object.updateExistingInXBookmarks [as UpdateExistingInXBookmarks] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2954:23) at Object.bookmarksUpdated [as Updated] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3869:26) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3565:55 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:154:326 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:52:3
2021-02-08 23:14:15.152	[trace]	{"bookmark":{"bookmarkbar":false,"dateAdded":1612825994861,"description":"","id":"1915","index":12,"nickname":"","parentId":"1","partner":"","speeddial":false,"thumbnail":"","title":"Feedly","trash":false,"url":"https://feedly.com/"},"container":"[xbs] Toolbar","indexPath":[12],"type":3}
2021-02-08 23:14:15.159	[trace]	Sync ll3mvx (pull) queued
2021-02-08 23:14:15.164	[trace]	Processing sync ll3mvx (0 in queue)
2021-02-08 23:14:15.728	[trace]	Local population completed in 0.256s
2021-02-08 23:14:15.748	[trace]	Local sync data refreshed
2021-02-08 23:16:27.386	[trace]	Starting up
2021-02-08 23:16:27.424	[trace]	{"checkForAppUpdates":true,"displayHelp":false,"displayOtherSyncsWarning":false,"displayPermissions":false,"lastUpdated":"2021-02-08T23:08:30.154Z","syncBookmarksToolbar":true,"syncEnabled":true,"syncId":"c05f83d2fd9648c5971463238a2e4d18","syncVersion":"1.5.2","appVersion":"1.5.2","platform":{"name":"chrome","version":"88.0.4324","mobile":false,"os":"Windows 10"}}
2021-02-08 23:16:35.327	[trace]	onChanged event detected
2021-02-08 23:16:36.337	[trace]	Sync 138egig (push) queued
2021-02-08 23:16:36.620	[trace]	Processing sync 138egig (0 in queue)
2021-02-08 23:16:36.641	[trace]	Sync 138egig failed
2021-02-08 23:16:36.652	[error]	bookmarks.sync: [10111] XBookmarkNotFound	Error at Object.updateExistingInXBookmarks [as UpdateExistingInXBookmarks] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2954:23) at Object.bookmarksUpdated [as Updated] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3869:26) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3565:55 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:154:326 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:52:3
2021-02-08 23:16:36.661	[trace]	{"bookmark":{"bookmarkbar":false,"dateAdded":1612826055569,"description":"","id":"2117","index":12,"nickname":"","parentId":"1","partner":"","speeddial":false,"thumbnail":"","title":"Feedly","trash":false,"url":"https://feedly.com/"},"container":"[xbs] Toolbar","indexPath":[12],"type":3}
2021-02-08 23:16:36.668	[trace]	Sync vslda5 (pull) queued
2021-02-08 23:16:36.679	[trace]	Processing sync vslda5 (0 in queue)
2021-02-08 23:16:37.268	[trace]	Local population completed in 0.281s
2021-02-08 23:16:37.293	[trace]	Local sync data refreshed
2021-02-08 23:19:39.188	[trace]	onChanged event detected
2021-02-08 23:19:40.202	[trace]	Sync i84i66 (push) queued
2021-02-08 23:19:40.478	[trace]	Processing sync i84i66 (0 in queue)
2021-02-08 23:19:40.495	[trace]	Sync i84i66 failed
2021-02-08 23:19:40.504	[error]	bookmarks.sync: [10111] XBookmarkNotFound	Error at Object.updateExistingInXBookmarks [as UpdateExistingInXBookmarks] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2954:23) at Object.bookmarksUpdated [as Updated] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3869:26) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3565:55 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:154:326 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:52:3
2021-02-08 23:19:40.513	[trace]	{"bookmark":{"bookmarkbar":false,"dateAdded":1612826197101,"description":"","id":"2318","index":12,"nickname":"","parentId":"1","partner":"","speeddial":false,"thumbnail":"","title":"Feedlu","trash":false,"url":"https://feedly.com/"},"container":"[xbs] Toolbar","indexPath":[12],"type":3}
2021-02-08 23:19:40.518	[trace]	Sync jc2yyq (pull) queued
2021-02-08 23:19:40.526	[trace]	Processing sync jc2yyq (0 in queue)
2021-02-08 23:19:41.124	[trace]	Local population completed in 0.267s
2021-02-08 23:19:41.149	[trace]	Local sync data refreshed
</details>

**Comment by nero120** [comment]
Vivaldi is not yet a supported browser, it's on the roadmap though (see #6).
