### ISSUE TITLE
Sync error. Local data has been refreshed, please redo previous unsynced changes

### ISSUE THREAD

**Issue by iago-pssjd** [xbrowsersync/app#287]
First, this seems to be another variant of issues #159, #218, #265 and #270 (and related also to #201 and #203).

**Describe the issue you are experiencing**
I have the app installed in firefox and in Vivaldi. In firefox it works, but in Vivaldi, when I try to add a new bookmark in the usual form (that is, using the Vivaldi tools  for adding bookmarks, not the xbrowsersync app) I get the error: `Sync error Local data has been refreshed, please redo previous unsynced changes` and the current URL is not added to the list of bookmarks, which keeps in its previous state.

1. Install and sync xbrowsersync on firefox
2. Install and sync xbrowsersync on Vivaldi with ID previously created
3. Try to add a new bookmark in Vivaldi with self Vivaldi tools for adding bookmarks.

**Screenshots**
![image](https://user-images.githubusercontent.com/40892925/110322304-36f9b300-8013-11eb-8b00-0f6d954905e5.png)

**Desktop browser**
Please complete the following information for all affected desktop browsers:

- OS:  Debian GNU/Linux 9.12 (stretch)
- Browser Vivaldi
- Version 3.6.2165.40 

**Application log**
Please include the logs from the affected clients:

<details>
<summary>Log entries</summary>

```
2021-03-08 12:38:42.763	[trace]	onCreated event detected
2021-03-08 12:38:44.186	[trace]	Sync fy0sl (push) queued
2021-03-08 12:38:45.791	[trace]	Do not have permission to read active tab content
2021-03-08 12:38:46.102	[trace]	Processing sync fy0sl (0 in queue)
2021-03-08 12:38:46.116	[trace]	Sync fy0sl failed
2021-03-08 12:38:46.123	[error]	bookmarks.sync: [10111] XBookmarkNotFound	TypeError: Cannot read property '3' of undefined at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2555:41 at Array.reduce (<anonymous>) at Object.addNewInXBookmarks [as AddNewInXBookmarks] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2554:49) at Object.bookmarksCreated [as Created] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3844:26) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3555:55 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:154:326 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:52:3
2021-03-08 12:38:46.126	[trace]	{"bookmark":{"bookmarkbar":false,"dateAdded":1615207122754,"index":11,"nickname":"","parentId":"21764","partner":"","speeddial":false,"thumbnail":"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAEOAUoDASIAAhEBAxEB/8QAGwABAAIDAQEAAAAAAAAAAAAAAAMFAQIEBwb/xABLEAABAwIDAwYICggFBQEBAAABAAIDBBEFEiETMVEGQWFxkdEUFRciMjNTkiNVYnKBlKGxstIHNDVDdIKTwSVCUlTTFiRE4fBzZP/EABoBAQEBAQADAAAAAAAAAAAAAAABAgMEBQb/xAAvEQEAAQIFAgQFAwUAAAAAAAAAAQIDERQVUZESMQQTIWEyQVKh0SJxsSRCgcHw/9oADAMBAAIRAxEAPwD6OpwZseFy4hA989NFII3uDgNd126atvpfpVRM0Mlc1t7C1r79119JieKSVFFUUbZ4qeiq5xPsm2DI+hovo3W54lfPVeXwmTI4PaCAHDcbAC69BcimOz5W7FMfChREXNxEREBERAREQEREBERAREQEREBERAREQEU1JKIKuCZzc7Y5GvLeIBvZWgxWhLWF+GRl7Whu5pGgtz69vXvViInvLdNMT3nBSoTberHEa2kqadjKaiZTyB2ZzwBrpu03DoXPhtS2jrY53MLw0O83iS0gfaUwjHDFJiMcMXNdFeRYxSMZc4e3aOLXvyhoaXDhpcC9z9Nty1dieHvkLn4e43Y5tvM1cRYOva+nD/2tdMbtdFP1KVFeSYvQyOL34c0vuTq1lt5I0tzX3bjz8y4MSqaapdEaWm8HyghwFrG5vzKTTEdpSqmIj0lxEgb0XZhtaKJ8zzE2UvjLGh3o3uDr0WB7V3jFcPaHBmGtF9NzNRppu6LaW47ykUxPzKaaZj1lSJccVLVPZJUyvhYY43OJaw280cNF2Q18UeHQUzoCXxziYyaai98vYpERukRGPrKuvfciuZ8Uop2SF9Baoc5xEjQ02B0GhGpsBqekhdMeKYRNVvfUYe5ge/Pms12XzSLWtc3JuVrojdvopn+586itMSr6Kpp3R01AyB+ZpD2gDQXvfn1/+uuGklbBVQyvZnaxwcW8VmYiJwxYmIicMUKK4biVCGWfQGV9rF8mUudqLkm28i/VzLabFKB4zNw/LMXFxfZltSDa1rW0t9K10xu10U/UpUUlTI2WpmkY3K173ODbAWBN7aaKNYc33h/R1j5BDqqmcDzGRx+8KPyaY17aj953cvaLJZe4yVp9Dp1n35eL+TTGvbUfvO7k8mmNe2o/ed3L2iyWTJWjTbG08vF/JpjXtqP3ndyeTTGvbUfvO7l7RZLJkrRptjaeXi/k0xr21H7zu5PJpjXtqP3ndy9oslkyVo02xtPLxfyaY17aj953cnk0xr21H7zu5e0WSyZK0abY2nl4v5NMa9tR+87uTyaY17aj953cvaETJWjTbG08vF/JpjXtqP3ndyeTTGvbUfvO7l7QiZK0abY2nl4v5NMa9tR+87uTyaY17aj953cvaETJWjTbG08vF/JpjXtqP3ndyeTTGvbUfvO7l7QiZK0abY2nl4v5NMa9tR+87uTyaY17aj953cvaETJWjTbG08vF/JpjXtqP3ndyeTTGvbUfvO7l7QiZK0abY2nl4v5NMa9tR+87uTyaY17aj953cvaETJWjTbG08vF/JpjXtqP3ndyeTTGvbUfvO7l7QiZK0abY2nl4v5NMa9tR+87uTyaY17aj953cvaETJWjTbG08vF/JpjXtqP3ndyeTTGvbUfvO7l7QiZK0abY2nl4v5NMa9tR+87uTyaY17aj953cvaETJWjTbG08vF/JpjXtqP3ndyeTTGvbUfvO7l7QlkyVo02xtPLxfyaY17aj953cnk0xr21H7zu5e0WSyZK0abY2nl4v5NMa9tR+87uTyaY17aj953cvaLJZMlaNNsbTy8X8mmNe2o/ed3J5NMa9tR+87uXtFksmStGm2Np5eL+TTGvbUfvO7k8mmNe2o/ed3L2iyWTJWjTbG08iIi8t54iIgIiICIiAqblbW1GHYHPU0mfasLfQjzusXAGwsdekggcFcogpqCtq5+TVPVOj21TJFmcL7PmOuv/x3hc+B4Th8mDUD34XSOc6njcXOjaSSWjfor2p/VpfmH7lx8nv2Dhv8NF+AII/E2G/FVF/Sb3LQ4Phu1H+FUfon923o6FbrQ+uHzT94QV3ibDfiqi/pN7k8TYb8VUX9JvcrREFU7BsNsf8ACqL+k3uWI8Gw0xt/wqj3D903uVq70T1LEXq2dQQVvibDfiqi/pN7k8TYb8VUX9JvcrREFR4nw3a28VUfo+zbx6lv4mw34qov6Te5WP7/APl/ut0FX4mw34qov6Te5avwbDcjv8Ko93sm9ytlrJ6DuooKxmDYblH+FUe72Te5Z8TYb8VUX9JvcrNnoN6llBV+JsN+KqL+k3uWnifDdqR4qo/R9m3j1K3Wg9efmj70Fd4mw34qov6Te5PE2G/FVF/Sb3K0RB8FPydrxXzSxUVG2n2kjmtc5jgGWs0ZcnPqd/mkAa3JVxJh0NI7B5PAqSCq8IYHvgYG6ljr2sNy+jl9U/qKrcY9Zhn8Wz8LkFoNyINyICIiAiIgIiICIiAiIgIiICIiAiIgXWk0scMbpJXtZG0XLnEAD6VQ1dVs+WVHTGWpaJYS/LtTsjbPplA38+pG4WBsbdnKbD58TwiWnpXRMnJa5jpb2BBB3jUHp1Qd872vpJHscHNcwkEG4IsuXk9+wcN/hovwBc9Jhr6Xk5DRSSlj4YrOfAS25APP/wDX6Nyl5PR3wHDfOf8Aq0XP8gILNRn1w+afvCzs/lv7VGY/hh57/RPP0hBOi02fy39qbP5b+1Bs70T1LEXq2dQWro/NPnv7VrFH8G3z37hzoJkWmz+W/tTZ/Lf2oMfv/wCX+6kUGz+G9N/o8elSbP5b+1ButZPQd1FY2fy39q1kj8x3nv3HnQSM9BvUsqJkfmDz37uK22fy39qDdRj15+aPvWdn8t/ao9n8MfPf6PHpQTotNn8t/amz+W/tQZl9U/qKrcY9Zhn8Wz8Ll3Sx/Bv89+486r8WbaXDDmcf+7ZvPyXILYbkQbkQEREBERAREQEREBERAREQEREBERB8jijXeUTCCA4tNO8nzSRucN97adRIueK+uC+G5Rzil/SDg02SF7jG2H4QkZc7ni4NrA8Ad+trW1+qxrEPFmHvqjEZA0tFgbAXNrk8B1HqQddV+rS/MP3Lj5PfsHDf4aL8AUbcUhnwJldKDDHNFmAd51rg23LPJ6VgwHDdf/Gi/AEFmtD64fNP3hNqziozKzbDX/KebpCCdFptWcU2rOKDZ3onqWIvVs6gtXSsynX7FrFKzZt15ggmRabVnFNqzigfv/5f7rdQbVm23/5f7qTas4oN1rJ6DuorG1ZxWskrMjteYoJGeg3qWVEyVmRuvMttqzig3Wg9efmj702rOKj2rNsdf8v90E6LTas4ptWcUGZfVP6iq3GPWYZ/Fs/C5d0srNk/XmKr8Xe10uGAG/8A3bPwuQWw3Ig3IgIiICIiAiIgIiICIiAiIgIiICIiD4TE58n6SqAVTJDEG7OPbyRiMFzbh0YuHXzNLTmv0dH2ldR09fSSU1ZDHPBILOjkbcFfL4wyKTl9hLJcrjsS4MNiDbOb794OW1wTvy286/16Dm2EVLh2wp2COGKLIxjdA0AWAUHJ79g4b/DRfgC7Kn9Wl+YfuXHye/YOG/w0X4AgsFGfXD5p+8KRaH1w+afvCDdERBh3onqWIvVs6gsu9E9SxF6tnUEGyIiCP9//AC/3Ui0/f/y/3W6AtZPQd1FbLWT0HdRQZZ6DepZWGeg3qWUBRj15+aPvXDygxVmDYeauSPaMD2tLQ4A2O8i+8jfZcPJ3lHT409uSKWGZzHExvANrOtvHQQeGvEFB9AiIg1l9U/qKrcY9Zhn8Wz8LlZS+qf1FVuMeswz+LZ+FyC0G5EG5EBERAREQEREBERAREQEREBERAREQV8uE00uMwYm8O8JhjMTdxGU36NN/NZRcphWuwl7cM2nhLnsaMhtoXC9zvAtzjVWqIKWhfXScmoXPDhVmM5xVtyu594bex3cVPye2niHDbZP1aLj/AKAu+p/VpfmH7lx8nv2Dhv8ADRfgCDt+E+R9qjO02w9D0Tx4hTrQ+uHzT94QPhPkfanwnyPtW6IInbTKfQ+1Yi2mzb6G4cVK70T1LEXq2dQQY+E+R9qfCfI+1bogg+E23+T0enipPhPkfan7/wDl/ut0GnwnyPtWsm0yO9DceKiocRpK/beCTsl2LzG/KfRcOZQcocSjwjBKzEJWOkZTxl5a3eehB2M2mQehu6VFU1bKYxiomgiMjsjM7rZjwC58GxaDEMEo8RPwEdRG14bKcpF+bVV3KCso5Hx+fQTeBytNRtJReG50vYi17bjfUDQ82qaKqu0C/IeRqGHtXCysh8aOpGlgqBHmIDTa2+1/pBt0rM2MUkL3RkyFzYtrfZua0i1wA82bc8LqoHKrChWQukMET5IyHvfUQZogCbB2V5JvzAX362XSnw92rtSmMPpPhPkfanwnyPtXy7OUjqqBojnjil2mvgtJPVgs4Bwa0B3TYhbyVgqTVNdR8oauKew2Zj2DWAG9mm7COm5N10ylcfH6f9x906oX1TUNia5kksDHFjnZXOsbAamy5MWLjLhhOW3hbN3zXLg2lTG4PpOTTmStiETZZp4WuDANBmBcbJVy4rJV4X4ZR0cEHhTbmOpdI++V1tMgH2rFdnpjGJjmP4xXF9KNyINyLgoiIgIiICIiAiIgIiICIiAiIgIiICw5wa0lxAA1JKyuTE6CDEqR1PUhxjJDtDYgg3H28UE1Qb00ltbsO7qVZhVZT0XJ3C31UzImOgiaC42ucg/9n6F1NwqlbhkdAGHweNuVoLjftv0qoq+TlVU4TDQGvgYyIMayTwMOc3KANMziNRcHTnKsRjOA+lXG+tpm4lHSOnjFS6MubHfUi/8A6PYeBVZNg+KvkqHtxxzNqzI1racZYj/qb5179ZI13L52XkXjUmO0dbJylqHSU8D2NmFGwHUj0vOs42LrEjTW29dabdExjNcRz+Exeg3XHDidFN4Rs6qFwp3ZZTmAyHp+m4+g8F8PP+jqsnghhl5U4o6KObbFpJ87oJz3t1LEf6LMNacSzzGXxhKJZ9ptSSQb2B2l7X43XbyvDR3uTP7U+/vMfJMatn2GK8oMJwymllrsQpYmsgdUFplbmMYBJcG3uRYHcqil/SDyXkoaGobjFPkqjkjbqXZhoQQLluvHRcjf0f4ZC50seH4O6XY7Hz6Euuy1rWMlteO9d+F8mhS0dC2GnwimNO3NExmHAbFx1OU59DfnCf0kfVPEfn2+5+pR4/8Apd5OYVA6WLwyuayqbSO8HgcRmN9xOh3br6qzdy3L62WnpMAxucx0+3LvBsgva4b53PrzX6Lq7bh9a0WbU0I87NpRnfx9Pf0rfwXErW8Npbfwrv8AkTzfDR2tzP71fiIMJ3fBw8reWdVytoIIeSMsWFz0+eQzyZTGcxFy62m4aEc+471by1vLmpoqkxYVQUsu3DYgZQ5wj46ktPXcHoV8abFfDA3wml2Wzvn8FO++71im8ExH/eUv1V3/ACKx4q3T8Nqn7z8/eTpnd8JyY5I8rsHkxsNxPDo46wukYWMcbyE772Bbpz+d1K4dyYxqo8DGI4yZYo43CUAXNyDuDmkP63BfSeCYj/vKX6q7/kUc9LiYgkLKqlc8NNm+Cu1Nt3rFM7XEYU00x/iNsDph85Q8gjT4ZTUvjOQtilEmURkMAtbzWh1w75V/oVlJyPp53VIqKuqfG8gx/CPc6Pjq9zg6/SFYw0uJmFhfV0rXFouPBXaG3/6KTwTEf95S/VXf8ilXj/EVTj1fwdMOGLklhcVRtWQsHweTLsYiL29O+S+b6bdC66PB4KaWAiSpe+BpyuMzm5rk+kG2a76QtvBMR/3lL9Vd/wAihFNivhjm+E0uy2YIf4KdTc6es6lyq8Rdq71LhDodg8JpnQiprw10m0zCrkzA8A69wOjcpJMOD5qmQVVY0zMyZWzHKzdq0cx03qHwTEf95S/VXf8AIs+CYj/vKX6q7/kWfNr3MGThzoxTuFdWuEDCC10gIl3+npr9i1xj1mGfxbPwuUVVS4o2mlMVVSvkDCWt8FPnG2g9Ytm4dVzTUslVVQlsMglyMgLSSARa5eePBZqqmruq3G5ERZBERAREQEREBERAREQEREBERAREQEREBERAVbKa/wAfQNja4YcIHGRxDC0vvoBrmB577v7WSICIiCGsM7aWU0jY31Aadm2R1ml1tLngosHNWcKo/GQaK7Yt24aRbPbzrW03rrRARFy12I0dAIzW1MUAeSGmRwbeyDkBxT/qNwLGeKdgMpFr7S+t+f8AsrVVkOPYXNttnXQOMTNo8ZvRbxP0m3XosP5Q4RHGyR+I0oY8XaTILHfu7D2ILRceLmrGGVXi0NNZszss1rZrab9FwR8qsEfLsxiVODewLnZQTcjQnfuKtqWohq6eOemkbLDI0OY9puHA84QRYUao4dTeMABV7Nu1DbWz213dK6kRAVDJ48bjbcuzdhxmJuGtFo8jdDrffnsRz79FfIgBERBx4qKs0zfF7miUSxl12g3ZnGcaka5bqLADXOwyJ2KNc2qJcXNdlzNFzYHL5pNrahWKICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgLhxLCaLE3wmugbOIr5WvJy6ixuNx3c67kQVcXJ/CojIY6GBrpGGNxtq4Egm54kgG++4uoIOSmCQmIsw6AuisWucC5wI3G55+fruVdogqP+msG2gk8W02cOzB2TUFWNFSwUVLHT0kTYoIxlYxosAFMiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiIgIiICIiAiKJ0hDiNEEqKHaO6OxNo7o7EEyKHaO6OxNo7o7EEyKHaO6OxNo7o7EEyKHaO6OxNo7o7EEyKHaO6OxNo7o7EEyKHaO6OxNo7o7EEyKHaO6OxNo7o7EEyKHaO6OxNo7o7EEyKHaO6OxNo7o7EEyKHaO6OxNo7o7EEyKHaO6OxNo7o7EEyKHaO6OxNo7o7EEyKHaO6OxNo7o7EEyLDTcArKAiIgIiICIiAiIgIiICIiAuSrY6WOVjJHROcCA9u9vSF1rUsaSTZBWxUjo4HxmeSUvcCXSG5A00H0D7VvFA9jnOMmYkEDTddxPHpHYu7Zt4HtTZt4HtQV8VM5kUjTM5xc0NBN9NN+/p+7gt6SAwNcHSvlu693c2m5duzbwPamzbwPaghRTbNvA9qbNvA9qCFFNs28D2ps28D2oIUU2zbwPamzbwPaghRTbNvA9qbNvA9qCFFNs28D2ps28D2oIUU2zbwPamzbwPaghRTbNvA9qbNvA9qCFFNs28D2ps28D2oIUU2zbwPamzbwPaghRTbNvA9qbNvA9qCFFNs28D2ps28D2oNmeiOpZQCw0RAREQEREBERAREQEREBERAXLUyshbJJM9rI2Auc5xsAOJXUq3GGNkoKtj4HVDXRuBiabF+m4dKR7iCTG8LjNpMSo2HfZ0zRw6ekdq6W1dO6MSNqIiwv2YcHixde2XrvzL5WjjoZpDFFyYbG4Na/aSx3G5oBOlybHjfTrtaQO8FtSw4A6OnDtq3Jlyhxc7W1tHaA/wAw151urpw9BaVVbT0uy28gbtSQznBs0uP0WBUZxSjEoi8JYZC5zMoOt22uPtCqpMSlqWPgdgczixljG75THabtAbWPQfoWGSwVNSInYI7aatu/S1st7m3V2c+qzhLE3KYnCVyMRoy/IKqEu00zcSQPtaR9BWoxOiIaTVwtLgHAOeGmxGbcejVcVM8NexzcGkhOa99NLudc6dZP8xWjGxTGJk2COEbR6bmA5LsANhv3AN+gJhJ5kLF2JUTXZTVwZr2y5wTe4G7rIWW4jRvtlqoTc2Azga3I+8ELhhw+jnqpDUYc2OUOkaCAcsjLt846AXOmmvP0riqYoIazJ4kdJK0Nf/2x8y2Y25gOtPT5txRcrnCjBeCvpCCRVQEAXPwg0Fr37NVl9bTMPwlREzUjzngc9lTxyOnflfgDo3yG2aQjL6BF3EDd/l+lds8FNHA+aPDxNI1+UsazUkkBxF94H9k9Cui5R6Thy72zxuqHwNeDMxoe5nOAb2P2HsUclbTRyOZJPGx7dCHOtzX+7VUgr545IBLgNVtza7oz5twXGwPaddNV3yRtxCOgfWYc85gS5kjh8Dcahw51GqenH9XZ0txKhc4tbWU5cN4Eo6v7qSCqhneWxPzEDNuI0uR97SF85LLAZJY4eTD5wyR0ZLWNDTlI5yOn7F2xYpVulzuwOrjkcGhznEG4u6wB6N/MNUhbk24jGnFeoqwV9UWZvF0zPNJIJub5bgCw110WBiNWZCwYXUNGb03HzcuYC+g4Em3QrhLj5lK0RVUddWSSsvRvhaSwFr2lxAJffUaf5W9WbqWYq+pL2OmpnMj3uAjcS0bIOI6Tm0+zeo1ExK0RcVfVz0xvDRTVLbAnZkXuXAWA6rnqCjo62qmdK2fD5YSyPMHZgWvdc+aL210GvSirFFVV+KTUjKa2HVM0kzXHZsILmkC+U20uuduM1+Y5sArg3mIc0k6gburX6EF6iq4cRq5BY4ZO07rl2l/O6L20GvSsSYlVMAIwupk825ycxyg2FxrqSPoVwlz8ynDH/UrVFWGuqy9rPAJGXeAXnzmhu0Dd2++Uk8B0reiqqmYsE8Bju0EnI4anNprwsNenpTBqKolcM9EdSysM9EdSyo0IiICIiAiIgIiICIiAiIgLnf6ZXQtSxpNyAggRT5G8AmRvAIIEU+RvAJkbwCCBFPkbwCZG8AggRT5G8AmRvAIIEU+RvAJkbwCCBFPkbwCZG8AggSynyN4BMjeAQQIp8jeATI3gEECKfI3gEyN4BBAinyN4BMjeAQQJZT5G8AmRvAIIEU+RvAJkbwCCBFPkbwCZG8Agyz0R1LKAWRAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQFxYxiEeF0MlVMx72MIBDLc5tckkADpK7VyYrh1NitE+krozJA+xLQ4t3G41GqCKLFaeTCY8QLxBDIzO3bkN3jTnsq+hfiNTQUtQ7E6dpmjY8tFMLDMAf8AV0q0jpIaLC/BqdpbFHGWtBJJ3HnK58D/AGBhf/4Q/hCDXY4h8awfVh+ZNjiHxrB9WH5lbIgqdjiHxrB9WH5lqI8QLiPGsGlv/GH5lcKNvrX9Q/ugrdjiHxrB9WH5k2OIfGsH1YfmVsiCoMWIAftWD6sPzI2PEHNB8awai/6sPzK2d6JWsXqmdQQVmxxD41g+rD8ybHEPjWD6sPzK2RBTujxAOaPGsGv/APMPzLbY4h8awfVh+ZWT/WR9Z+5SIKnY4h8awfVh+ZNjiHxrB9WH5lbIgp2x4gS7/FYNDb9WH5ltscQ+NYPqw/MrOP0pPnf2C3QVOxxD41g+rD8y1fHiDWk+NYNB/th+ZXC0m9U/qQfDP5TVTMRkpTWwODJXxFzGNJOUC5sXDcSAbmwvvNja8hrKxrsOmNbFNDUyNaYzT5HWc0n/AFGx0X0FlWY167Df4tv4XILMbkQbkQEREBERAREQEREH/9k=","title":"A Practical Guide to Mixed Models in R | Julia Pilowsky","trash":false,"url":"https://www.juliapilowsky.com/2018/10/19/a-practical-guide-to-mixed-models-in-r/","tags":null},"container":"[xbs] Toolbar","indexPath":[7,2,3,11],"type":1}
2021-03-08 12:38:46.131	[trace]	Sync 8007v6 (pull) queued
2021-03-08 12:38:46.141	[trace]	Processing sync 8007v6 (0 in queue)
2021-03-08 12:38:47.581	[trace]	Local population completed in 0.693s
2021-03-08 12:38:47.598	[trace]	Local sync data refreshed
```

</details>

**Comment by wyl-i** [comment]
Same with me:
after i installed xbrowsersync app in firefox 86.0 (64-bit) on my desktop (Ubuntu 20.04.2 LTS)  and on my phone (oneplus 5T).
initially everything worked fine and i could sync between my desktop and my phone.

But after a while (restarted my desktop and got the same message: "Local data has been refreshed, please redo previous unsynced changes") i saw that all my desktop bookmarkfolders in firefox where empty (?) and all my (hundreds of) bookmarks stayed outside of their folders.
But at the same time on my phone everything looked normal: all bookmarks stayed inside their folders where they belong.

I tried to sort out this mess on my desktop-firefox by restoring my backup, but that did not change anything: every bookmark stayed outside its folder (hierarchy) in a very long list.

What todo?

**Comment by jason076** [comment]
I am getting the same Error message in chromium (xbrowsersync 1.5.2) on archlinux if I try to move a subfolder from a folder in the bookmark bar to the bookmark bar itself.

**Comment by aspiers** [comment]
[**@jason076**](https://github.com/jason076) commented on [April 2, 2021 9:08 AM](https://github.com/xbrowsersync/app/issues/287#issuecomment-812404396 "2021-04-02T08:08:48Z - Replied by Github Reply Comments"):
> I am getting the same Error message in chromium (xbrowsersync 1.5.2) on archlinux if I try to move a subfolder from a folder in the bookmark bar to the bookmark bar itself.

I am seeing precisely the same thing in Chromium and Brave on openSUSE Linux.  Unfortunately this is a bit of a deal-breaker in usability :-/

**Comment by iago-pssjd** [comment]
I get this error with Vivaldi browser, but xbrowsersync in Brave works fine for me.

**Comment by mwoodfnc** [comment]
I also experience this error.  I had previously been syncing Chrome and Firefox. Have recently added Vivaldi, and am now getting tis error when I try to remove bookmarks from my bookmarks bar.

**Comment by nero120** [comment]
@iago-pssjd @mwoodfnc Vivaldi is not yet supported (see #6)

**Comment by dr-axen** [comment]
I'm having the same issue on Linux Mint 20.1 with Vivaldi browser. Anytime I'm trying to add or remove a bookmark, I'm getting this popup and the change gets reverted.

**Comment by nero120** [comment]
> @iago-pssjd @mwoodfnc Vivaldi is not yet supported (see #6).

@dr-axen literally right above your post!

**Comment by dr-axen** [comment]
Duh! This is what I get for skimming through the posts... If anyone is interested though, I found a workaround. Update your bookmarks in a supported browser, and Vivaldi will get the changes.

**Comment by nero120** [comment]
Since Vivaldi is not yet supported I'm going to close this issue. Please refer to [here](https://github.com/xbrowsersync/app/wiki/Supported-browsers-and-operating-systems) for supported browsers/platforms, and follow #6 for updates on Vivaldi support.

**Comment by acuteaura** [comment]
This bug is still present in other browsers (librewolf here, but above is chromium) when moving bookmarks to subfolders. Please reopen.

**Comment by acuteaura** [comment]
#474 seems to be a recent report of this issue.
