### ISSUE TITLE
Connectivity Issue with Wireguard Interface

### ISSUE THREAD

**Issue by Spoons** [xbrowsersync/app#320]
**Describe the issue you are experiencing**
Unable to connect to Xbrowsersync instance over Wireguard on Android. 
When trying to connect, the app displays 'Connection to service lost.' 
The web interface is accessible over the browser.

**How can the issue be reproduced?**
Install Wireguard android app and connect to a Wireguard gateway. 
Forward connections within the VPN subnet over Wireguard interface for all applications. 
Ensure DNS forwarding over VPN is disabled.
Point the app towards the server over the Wireguard interface using IP address and port.
Press 'sync'
Error message observed.
 
**Mobile device**
- Device: OnePlus
- OS: Lineage
- Version 18.1

**Application log**
```
2021-07-03 17:44:56.519	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-07-03 17:44:58.962	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-07-03 17:45:00.436	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)%                                                                                  
```

Thank you for the work done on this project.

**Comment by nero120** [comment]
Hmm, looks like a lower level issue. Could be the WebView container that Cordova uses - could you try installing the [InAppBrowser](https://play.google.com/store/apps/details?id=com.ionicframework.inappbrowser440939) app and see if you can browser web sites when Wireguard is enabled?

**Comment by Spoons** [comment]
Just tried it. I was able to access services over the wireguard tunnel / interface with the InAppBrowser tool without issue.
