### ISSUE TITLE
1.6.0 beta (Android) does not accept a sync upgraded with 1.6.0 beta (desktop)

### ISSUE THREAD

**Issue by olavinto** [xbrowsersync/app#333]
When I try to sing in to my sync in the 1.6.0 beta on Android, I get the following error:
"Sync version not supported. This ID cannot be synced with this version of xBrowserSync as the sync has been upgraded to a later version."

I have upgraded my sync when I signed in on desktop like it should be and I have installed the latest xBrowserSync beta on my Android devices as well. My bookmarks are synced and the beta addons sync with Firefox, Firefox Nightly and Chrome.

Edge does not want to log in but it seems to sync fine once when first logged in but immediately after that it reverts back to signed out with an error "Something went wrong" (this should probably be a separate issue).

I have also taken a manual backup of my bookmarks, created a new sync and then restored the backup but the problem remained.

**Desktop browser**
- OS: Windows 11 Dev Channel Preview
- Browser: Chrome, Firefox, Firefox Nightly, Edge, Edge Beta
- Version: v1.6.0 beta 21

**Mobile devices**
- Device: OnePlus 8T, Samsung Galaxy Tab S5e
- OS: Android 11 (both)
- Version: v1.6.0 beta 21

**Android log**
<details>
<summary>Log entries from Android</summary>
2021-08-30 14:10:39.371	[trace]	Upgraded to 1.6.0
2021-08-30 14:10:39.425	[trace]	Starting up
2021-08-30 14:10:39.468	[trace]	{"appVersion":"v1.6.0-beta.21","checkForAppUpdates":true,"platform":{"name":"Android","device":"samsung SM-T725"},"serviceUrl":"https://api.xbrowsersync.org","syncEnabled":false}
2021-08-30 14:17:42.337	[error]	Possibly unhandled rejection: {"logged":false}Error (Ce): at compareVersions.compare (webpack://xbrowsersync-app/src/modules/app/app-login/app-login.component.ts:258:20) at isFunction (webpack://xbrowsersync-app/node_modules/angular/angular.js:18075:36) at nextTick(function (webpack://xbrowsersync-app/node_modules/angular/angular.js:18123:39) at flushApplyAsync (webpack://xbrowsersync-app/node_modules/angular/angular.js:19242:17) at clearPhase (webpack://xbrowsersync-app/node_modules/angular/angular.js:19630:23) at resolvePromise (webpack://xbrowsersync-app/node_modules/angular/angular.js:13473:46) at isDefined (webpack://xbrowsersync-app/node_modules/angular/angular.js:13730:6) at onload (webpack://xbrowsersync-app/node_modules/angular/angular.js:13635:8)
2021-09-05 09:05:12.902	[trace]	Starting up
2021-09-05 09:05:13.055	[trace]	{"syncId":"014c6047ab164c97af5e1b9f7ba07931","appVersion":"v1.6.0-beta.21","checkForAppUpdates":true,"platform":{"name":"Android","device":"samsung SM-T725"},"serviceUrl":"https://api.xbrowsersync.org","syncEnabled":false}
2021-09-05 09:05:24.729	[error]	Possibly unhandled rejection: {"logged":false}Error (Ce): at compareVersions.compare (webpack://xbrowsersync-app/src/modules/app/app-login/app-login.component.ts:258:20) at isFunction (webpack://xbrowsersync-app/node_modules/angular/angular.js:18075:36) at nextTick(function (webpack://xbrowsersync-app/node_modules/angular/angular.js:18123:39) at flushApplyAsync (webpack://xbrowsersync-app/node_modules/angular/angular.js:19242:17) at clearPhase (webpack://xbrowsersync-app/node_modules/angular/angular.js:19630:23) at resolvePromise (webpack://xbrowsersync-app/node_modules/angular/angular.js:13473:46) at isDefined (webpack://xbrowsersync-app/node_modules/angular/angular.js:13730:6) at onload (webpack://xbrowsersync-app/node_modules/angular/angular.js:13635:8)
</details>

**Edge log**
<details>
<summary>Log entries from Edge</summary>
2021-09-05 08:28:33.054	[trace]	Installed 1.6.0.21
2021-09-05 08:28:33.058	[trace]	Starting up
2021-09-05 08:28:33.076	[trace]	{"appVersion":"1.6.0.21","checkForAppUpdates":true,"platform":{"name":"edge","version":"94.0.992","os":"Windows 10","type":"browser"},"serviceUrl":"https://api.xbrowsersync.org","syncBookmarksToolbar":true,"syncEnabled":false}
2021-09-05 08:28:43.978	[trace]	Optional permissions granted
2021-09-05 08:28:57.428	[trace]	Sync eb3oam (LOCAL) queued
2021-09-05 08:28:57.433	[trace]	Processing sync eb3oam (0 waiting in queue)
2021-09-05 08:28:58.254	[trace]	1184 bookmarks populated in 0.643s
2021-09-05 08:28:58.295	[warn]	Sync eb3oam failed
2021-09-05 08:28:58.564	[error]	Error (ge): ge at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:115:79) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:119:49) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:119:49) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at this.settingsSvc.syncBookmarksToolbar().then( (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:208:22)
2021-09-05 08:28:58.856	[error]	Possibly unhandled rejection: {}TypeError (TypeError): r[e.message] is not a constructor at angular.isUndefined (webpack://xbrowsersync-app/src/modules/webext/shared/webext-platform/webext-platform.service.ts:331:46)
2021-09-05 08:29:10.198	[trace]	Sync ocgm7r (LOCAL) queued
2021-09-05 08:29:10.203	[trace]	Processing sync ocgm7r (0 waiting in queue)
2021-09-05 08:29:11.041	[trace]	1184 bookmarks populated in 0.635s
2021-09-05 08:29:11.082	[warn]	Sync ocgm7r failed
2021-09-05 08:29:11.301	[error]	Error (ge): Cannot read properties of undefined (reading '0') at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:115:79) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:119:49) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:119:49) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at this.settingsSvc.syncBookmarksToolbar().then( (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:208:22)
2021-09-05 08:29:11.594	[error]	Possibly unhandled rejection: {}TypeError (TypeError): r[e.message] is not a constructor at angular.isUndefined (webpack://xbrowsersync-app/src/modules/webext/shared/webext-platform/webext-platform.service.ts:331:46)
2021-09-05 08:32:20.665	[trace]	Sync 18r2cs9 (LOCAL) queued
2021-09-05 08:32:20.670	[trace]	Processing sync 18r2cs9 (0 waiting in queue)
2021-09-05 08:32:21.492	[trace]	1185 bookmarks populated in 0.649s
2021-09-05 08:32:21.541	[warn]	Sync 18r2cs9 failed
2021-09-05 08:32:21.900	[error]	Error (ge): Cannot read properties of undefined (reading '0') at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:115:79) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:119:49) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:119:49) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at this.settingsSvc.syncBookmarksToolbar().then( (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:208:22)
2021-09-05 08:32:22.191	[error]	Possibly unhandled rejection: {}TypeError (TypeError): r[e.message] is not a constructor at angular.isUndefined (webpack://xbrowsersync-app/src/modules/webext/shared/webext-platform/webext-platform.service.ts:331:46)
2021-09-05 08:45:29.229	[trace]	Sync rkxv9k (LOCAL) queued
2021-09-05 08:45:29.236	[trace]	Processing sync rkxv9k (0 waiting in queue)
2021-09-05 08:45:30.053	[trace]	1185 bookmarks populated in 0.639s
2021-09-05 08:45:30.096	[warn]	Sync rkxv9k failed
2021-09-05 08:45:30.314	[error]	Error (ge): Cannot read properties of undefined (reading '0') at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:115:79) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:119:49) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:119:49) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at this.settingsSvc.syncBookmarksToolbar().then( (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:208:22)
2021-09-05 08:45:30.604	[error]	Possibly unhandled rejection: {}TypeError (TypeError): r[e.message] is not a constructor at angular.isUndefined (webpack://xbrowsersync-app/src/modules/webext/shared/webext-platform/webext-platform.service.ts:331:46)
2021-09-05 08:46:55.690	[trace]	Sync cmyfzn (LOCAL) queued
2021-09-05 08:46:55.696	[trace]	Processing sync cmyfzn (0 waiting in queue)
2021-09-05 08:46:56.498	[trace]	1185 bookmarks populated in 0.626s
2021-09-05 08:46:56.538	[warn]	Sync cmyfzn failed
2021-09-05 08:46:56.736	[error]	Error (ge): Cannot read properties of undefined (reading '0') at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:115:79) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:119:49) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:119:49) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at this.settingsSvc.syncBookmarksToolbar().then( (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:208:22)
2021-09-05 08:46:57.031	[error]	Possibly unhandled rejection: {}TypeError (TypeError): r[e.message] is not a constructor at angular.isUndefined (webpack://xbrowsersync-app/src/modules/webext/shared/webext-platform/webext-platform.service.ts:331:46)
2021-09-05 08:46:59.602	[trace]	Sync lwuiny (LOCAL) queued
2021-09-05 08:46:59.609	[trace]	Processing sync lwuiny (0 waiting in queue)
2021-09-05 08:47:00.400	[trace]	1185 bookmarks populated in 0.622s
2021-09-05 08:47:00.439	[warn]	Sync lwuiny failed
2021-09-05 08:47:00.679	[error]	Error (ge): Cannot read properties of undefined (reading '0') at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:115:79) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:119:49) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:119:49) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at this.settingsSvc.syncBookmarksToolbar().then( (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:208:22)
2021-09-05 08:47:00.967	[error]	Possibly unhandled rejection: {}TypeError (TypeError): r[e.message] is not a constructor at angular.isUndefined (webpack://xbrowsersync-app/src/modules/webext/shared/webext-platform/webext-platform.service.ts:331:46)
2021-09-05 08:50:14.629	[trace]	Sync 1e8hod8 (LOCAL) queued
2021-09-05 08:50:14.634	[trace]	Processing sync 1e8hod8 (0 waiting in queue)
2021-09-05 08:50:15.437	[trace]	1185 bookmarks populated in 0.629s
2021-09-05 08:50:15.478	[warn]	Sync 1e8hod8 failed
2021-09-05 08:50:15.676	[error]	Error (ge): Cannot read properties of undefined (reading '0') at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:115:79) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:119:49) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:119:49) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:113:29) at this.settingsSvc.syncBookmarksToolbar().then( (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:208:22)
2021-09-05 08:50:15.999	[error]	Possibly unhandled rejection: {}TypeError (TypeError): r[e.message] is not a constructor at angular.isUndefined (webpack://xbrowsersync-app/src/modules/webext/shared/webext-platform/webext-platform.service.ts:331:46)
2021-09-05 08:59:29.663	[trace]	Sync 18hzae7 (LOCAL) queued
2021-09-05 08:59:29.669	[trace]	Processing sync 18hzae7 (0 waiting in queue)
2021-09-05 08:59:29.808	[warn]	Decryption failed
2021-09-05 08:59:29.814	[warn]	Sync 18hzae7 failed
2021-09-05 08:59:30.114	[error]	Possibly unhandled rejection: {}TypeError (TypeError): r[e.message] is not a constructor at angular.isUndefined (webpack://xbrowsersync-app/src/modules/webext/shared/webext-platform/webext-platform.service.ts:331:46)
2021-09-05 08:59:43.224	[trace]	Downloaded file E:\oskar\Downloads\Common\352990ab-3d03-4656-966a-4e4cb43cde34.txt
2021-09-05 09:00:48.088	[trace]	Sync 3c7y13 (LOCAL) queued
2021-09-05 09:00:48.095	[trace]	Processing sync 3c7y13 (0 waiting in queue)
2021-09-05 09:00:48.221	[warn]	Decryption failed
2021-09-05 09:00:48.227	[warn]	Sync 3c7y13 failed
2021-09-05 09:00:48.527	[error]	Possibly unhandled rejection: {}TypeError (TypeError): r[e.message] is not a constructor at angular.isUndefined (webpack://xbrowsersync-app/src/modules/webext/shared/webext-platform/webext-platform.service.ts:331:46)
</details>

**Comment by arno-haas** [comment]
I have the same issue! thx for detailed report

**Comment by rogthefrog** [comment]
Same issue.

Desktop browser

OS: Windows 10 Pro 21H1 build 19043.1083
Browser: Brave Version: v1.6.0 beta 21

Mobile device

Device: Samsung Tab S2 8
OS: Lineage OS Android 10
Version: QQ3A.200805.001

**Comment by olavinto** [comment]
How goes it? It seems that there hasn't been much happening here for a while.

**Comment by nero120** [comment]
This is resolved by 072237fc9d9eba3e3342b063893c94b8f18d019f.

Work and family are keeping me very busy so I don't have a lot of spare time. I still fully intend to continue this project but I simply don't have as much time available time these days, so I do what I can with what I've got.

I fully intend on getting v1.6.0 out as soon as I can but there are a couple of sync bugs that I need to resolve. This release has taken far longer than I originally planned or hoped, so apologies for that.

**Comment by olavinto** [comment]
> 
> 
> This is resolved by [072237f](https://github.com/xbrowsersync/app/commit/072237fc9d9eba3e3342b063893c94b8f18d019f).
> 
> Work and family are keeping me very busy so I don't have a lot of spare time. I still fully intend to continue this project but I simply don't have as much time available time these days, so I do what I can with what I've got.

Good to know that this has been fixed and also good to hear that you're still alive and kicking. Just take your time! :-)

**Comment by rogthefrog** [comment]
Thanks so much @nero120

**Comment by nero120** [comment]
New beta release that includes this fix: https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.22

**Comment by AuthenticPumpkin** [comment]
> Thanks guys, here's a new beta release for you that includes this fix: https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.22

You rock @nero120, the fix works like magic. Thank you so much for all the time you put into this for us :)
