### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by gw73** [xbrowsersync/app#344]
**Describe the issue you are experiencing**
Installed Xbrowser on Firefox and on android mobile, both working well, tried installing on Chrome and have gotten several errors, including FailedRemoveLocalBookmarks,and something went wrong.

**How can the issue be reproduced?**

1.Remove the xbrowser app
2.close and reopen chrome
3. Download xbrowser
4. enter my password and sync id 
3. error pops up after a bit of trying to sync
4. 

**Screenshots**
!
![error 2021-10-28 085643](https://user-images.githubusercontent.com/93330091/139271673-a60cfbde-001b-4e13-8747-2567643940e8.jpg)

**Desktop browser**
Please complete the following information for all affected desktop browsers:
Windows 10 pro
Chrome Version 95.0.4638.54 (Official Build) (64-bit)
xbrowser ver. 1.5.2

**Mobile device**
Please complete the following information for all affected mobile devices:

- Device: [e.g. Samsung Galaxy S10]
- OS: [e.g. Android 9 Pie]
- Version [e.g. v1.5.0]

**Application log**
Please include the logs from the affected clients:

<details>
<summary>Log entries</summary>

```
Download the Application log from the Settings panel and paste the contents here.
```

2021-10-28 13:35:25.036	[warn]	Missing container: other bookmarks
2021-10-28 13:36:23.407	[trace]	Optional permissions granted
2021-10-28 13:44:54.063	[error]		Error: [10006] DailyNewSyncLimitReached at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:1818:38 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:151:185) at m.$apply (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:155:35) at k (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:106:129) at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:111:206) at XMLHttpRequest.y.onload (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:112:125)
2021-10-28 13:45:28.171	[trace]	Sync 4cd8bn (pull) queued
2021-10-28 13:45:28.175	[trace]	Processing sync 4cd8bn (0 in queue)
2021-10-28 13:45:29.622	[warn]	Missing container: other bookmarks
2021-10-28 13:45:29.627	[trace]	Sync 4cd8bn failed
2021-10-28 13:45:29.631	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2021-10-28 13:45:29.634	[trace]	Sync k9jg8h (pull) queued
2021-10-28 13:45:29.639	[trace]	Processing sync k9jg8h (0 in queue)
2021-10-28 13:45:30.129	[warn]	Missing container: other bookmarks
2021-10-28 13:45:30.133	[trace]	Sync k9jg8h failed
2021-10-28 13:45:30.137	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2021-10-28 13:53:07.426	[trace]	Sync 1v9aon4 (pull) queued
2021-10-28 13:53:07.429	[trace]	Processing sync 1v9aon4 (0 in queue)
2021-10-28 13:53:08.295	[warn]	Missing container: other bookmarks
2021-10-28 13:53:08.302	[trace]	Sync 1v9aon4 failed
2021-10-28 13:53:08.306	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2021-10-28 13:53:08.311	[trace]	Sync 1vqs8mz (pull) queued
2021-10-28 13:53:08.316	[trace]	Processing sync 1vqs8mz (0 in queue)
2021-10-28 13:53:08.834	[warn]	Missing container: other bookmarks
2021-10-28 13:53:08.839	[trace]	Sync 1vqs8mz failed
2021-10-28 13:53:08.843	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2021-10-28 13:54:35.049	[trace]	Sync 1v4uehk (pull) queued
2021-10-28 13:54:35.052	[trace]	Processing sync 1v4uehk (0 in queue)
2021-10-28 13:54:35.803	[warn]	Missing container: other bookmarks
2021-10-28 13:54:35.807	[trace]	Sync 1v4uehk failed
2021-10-28 13:54:35.811	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2021-10-28 13:54:35.815	[trace]	Sync 1k39120 (pull) queued
2021-10-28 13:54:35.819	[trace]	Processing sync 1k39120 (0 in queue)
2021-10-28 13:54:36.301	[warn]	Missing container: other bookmarks
2021-10-28 13:54:36.306	[trace]	Sync 1k39120 failed
2021-10-28 13:54:36.309	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2021-10-28 13:55:14.082	[trace]	Sync 109p6mx (pull) queued
2021-10-28 13:55:14.086	[trace]	Processing sync 109p6mx (0 in queue)
2021-10-28 13:55:14.861	[warn]	Missing container: other bookmarks
2021-10-28 13:55:14.867	[trace]	Sync 109p6mx failed
2021-10-28 13:55:14.871	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2021-10-28 13:55:14.876	[trace]	Sync 136scp4 (pull) queued
2021-10-28 13:55:14.880	[trace]	Processing sync 136scp4 (0 in queue)
2021-10-28 13:55:15.363	[warn]	Missing container: other bookmarks
2021-10-28 13:55:15.366	[trace]	Sync 136scp4 failed
2021-10-28 13:55:15.370	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2021-10-28 13:55:34.032	[trace]	Sync 3mtk0w (pull) queued
2021-10-28 13:55:34.036	[trace]	Processing sync 3mtk0w (0 in queue)
2021-10-28 13:55:34.836	[warn]	Missing container: other bookmarks
2021-10-28 13:55:34.840	[trace]	Sync 3mtk0w failed
2021-10-28 13:55:34.844	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2021-10-28 13:55:34.848	[trace]	Sync 10323al (pull) queued
2021-10-28 13:55:34.851	[trace]	Processing sync 10323al (0 in queue)
2021-10-28 13:55:35.331	[warn]	Missing container: other bookmarks
2021-10-28 13:55:35.336	[trace]	Sync 10323al failed
2021-10-28 13:55:35.340	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks

**Comment by nero120** [comment]
@gw73 this is a known issue with chromium browsers, in certain scenarios the "container" ids get changed in your browser profile and when this happens xBrowserSync has no way of finding the containers. This is an oversight of the web extensions bookmarks API which should provide a function to get the containers without having to query by id.

The only known solution is to create a new profile which will reset the bookmark ids and xBrowserSync should now sync without issue.
