### ISSUE TITLE
Can't create a new folder, when creating a new bookmark in both Edge and Chrome

### ISSUE THREAD

**Issue by timjoebrown** [xbrowsersync/app#347]
**Describe the issue you are experiencing**
A clear and concise description of your issue:
In both Edge and Chrome, if you would like to create a new folder, at time of creating a new bookmark, it creates the bookmark, but does not create the folder.

**How can the issue be reproduced?**
create a new bookmark.
while creating it, 
Click more
click new folder
name the folder
select folder
click save

outcome
no folder created, just bookmark

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Desktop browser**
Please complete the following information for all affected desktop browsers:

Windows 10
Chrome
Edge - chromium.

*
Download the Application log from the Settings panel and paste the contents here.

Tried to create a new folder Github-Test-creation, and bookmark github into it.

021-11-10 20:40:37.531	[trace]	onRemoved event detected
2021-11-10 20:40:38.570	[trace]	Sync 5w5oq0 (push) queued
2021-11-10 20:40:38.655	[trace]	Processing sync 5w5oq0 (0 in queue)
2021-11-10 20:40:39.055	[trace]	Remote bookmarks data updated at 2021-11-10T20:40:38.975Z
2021-11-10 20:40:46.581	[trace]	onCreated event detected
2021-11-10 20:40:47.615	[trace]	Sync wp6h79 (push) queued
2021-11-10 20:40:47.700	[trace]	Processing sync wp6h79 (0 in queue)
2021-11-10 20:40:48.028	[trace]	Remote bookmarks data updated at 2021-11-10T20:40:47.971Z
2021-11-10 20:41:06.072	[trace]	onCreated event detected
2021-11-10 20:41:06.118	[trace]	onMoved event detected
2021-11-10 20:41:07.107	[trace]	Sync 1uqse2m (push) queued
2021-11-10 20:41:07.154	[trace]	Sync 2jh03h (push) queued
2021-11-10 20:41:07.210	[trace]	Processing sync 1uqse2m (1 in queue)
2021-11-10 20:41:07.324	[trace]	Processing sync 2jh03h (0 in queue)
2021-11-10 20:41:07.331	[trace]	Sync 2jh03h failed
2021-11-10 20:41:07.339	[error]	bookmarks.sync: [10111] XBookmarkNotFound	TypeError: Cannot read properties of undefined (reading 'splice') at Object.addNewInXBookmarks [as AddNewInXBookmarks] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2563:29) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3865:65 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:154:326 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:52:3
2021-11-10 20:41:07.345	[trace]	{"container":"[xbs] Toolbar","indexPath":[99],"targetInfo":{"container":"[xbs] Toolbar","indexPath":[99,0],"bookmark":{"dateAdded":1636576846578,"id":"19300","index":0,"parentId":"19301","title":"GitHub: Where the world builds software · GitHub","url":"https://github.com/"},"syncChange":true},"type":4,"bookmark":{"dateAdded":1636576846578,"id":"19300","index":0,"parentId":"19301","title":"GitHub: Where the world builds software · GitHub","url":"https://github.com/"},"syncChange":true}
2021-11-10 20:41:07.352	[trace]	Sync 8awsmc (pull) queued
2021-11-10 20:41:07.356	[trace]	Processing sync 8awsmc (0 in queue)
2021-11-10 20:41:08.009	[trace]	Local population completed in 0.248s
2021-11-10 20:41:08.031	[trace]	Local sync data refreshed

</details>

**Comment by likeon** [comment]
Having the same issue on chrome when trying to move a freshly created bookmark:

> 2022-07-25 10:33:55.264	[trace]	Sync 1i0tsn0 (push) queued
> 2022-07-25 10:33:55.364	[trace]	Processing sync 1i0tsn0 (0 in queue)
> 2022-07-25 10:33:55.392	[trace]	Sync 1i0tsn0 failed
> 2022-07-25 10:33:55.397	[error]	bookmarks.sync: [10111] XBookmarkNotFound	TypeError: Cannot read properties of undefined (reading 'splice') at Object.removeExistingInXBookmarks [as RemoveExistingInXBookmarks] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2908:40) at Object.bookmarksMoved [as Moved] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3855:51) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3570:55 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:154:326 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:52:3
> 2022-07-25 10:33:55.402	[trace]	{"container":"[xbs] Toolbar","indexPath":[10,5],"targetInfo":{"container":"[xbs] Toolbar","indexPath":[7],"bookmark":{"dateAdded":1658745202063,"id":"1697","index":7,"parentId":"1","title":"Snapdrop","url":"https://snapdrop.net/"},"syncChange":true},"type":4,"bookmark":{"dateAdded":1658745202063,"id":"1697","index":7,"parentId":"1","title":"Snapdrop","url":"https://snapdrop.net/"},"syncChange":true}
> 2022-07-25 10:33:55.407	[trace]	Sync 1ldhsx7 (pull) queued
> 2022-07-25 10:33:55.412	[trace]	Processing sync 1ldhsx7 (0 in queue)
> 2022-07-25 10:33:55.624	[trace]	Local population completed in 0.063s
> 2022-07-25 10:33:55.635	[trace]	Local sync data refreshed

Fedora 36, Chrome 103.0.5060.114, xBrowserSync 1.5.2
