### ISSUE TITLE
Android: Connection to service lost, local network, self-hosted

### ISSUE THREAD

**Issue by nagyrobi** [xbrowsersync/app#356]
**Describe the issue you are experiencing**
Using my self hosted service inside my local network. Connecting without SSL due to issue https://github.com/xbrowsersync/api-docker/issues/20. Address is http://sync.internal.lan:8080 which is accessible from the same android phone.
Syncing with desktop browser extensions works OK. Firefox browser doesn't support the extension, so I am constrained to use the app, but that doesn't work either. 

**How can the issue be reproduced?**

1. Scan the code shown by the desktop plugin.
2. Enter the password, click `Sync`.
2. The message it throws: _Connection to service lost. Check your network connection and try again._

**Screenshots**
If applicable, add screenshots to help explain your problem:
![kép](https://user-images.githubusercontent.com/1550668/144081415-908af3a4-8632-4f6d-9f7f-25d0e8f65859.png)

**Desktop browser**
Please complete the following information for all affected desktop browsers:

- OS: Ubuntu 20.04
- Browser: Firefox
- Version: v94.0

**Mobile device**
Please complete the following information for all affected mobile devices:

- Device: OnlePlus 5T
- OS: Android 10

**Application log**
Please include the logs from the affected clients:

<details>
<summary>Log entries</summary>

```
2021-11-30 15:31:00.855	[trace]	Installed v1.5.2
2021-11-30 15:31:00.871	[trace]	Starting up
2021-11-30 15:31:01.010	[trace]	{"checkForAppUpdates":true,"appVersion":"1.5.2","displayHelp":true,"platform":{"name":"Android","device":"OnePlus ONEPLUS A5010"}}
2021-11-30 15:31:24.506	[trace]	Scanned: 8aa654f852824af393e6d58c1887b951|$$|http://sync.internal.lan:8080
2021-11-30 15:31:25.547	[trace]	Service url changed to: http://sync.internal.lan:8080
2021-11-30 15:31:25.594	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:31:25.691	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:31:40.135	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:33:36.100	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:33:47.344	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:33:53.560	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:34:02.390	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:34:07.813	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:34:08.511	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:34:09.005	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:34:09.259	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:34:09.466	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:34:09.660	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:34:09.830	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:34:10.016	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:34:10.201	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:34:10.389	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:34:10.554	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:34:10.800	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:34:11.003	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:51:59.651	[trace]	Starting up
2021-11-30 15:51:59.671	[trace]	{"displayHelp":false,"appVersion":"1.5.2","checkForAppUpdates":true,"serviceUrl":"http://sync.internal.lan:8080","syncId":"8aa654f852824af393e6d58c1887b951","platform":{"name":"Android","device":"OnePlus ONEPLUS A5010"}}
2021-11-30 15:51:59.875	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:52:00.147	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 15:52:14.441	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2021-11-30 16:02:56.068	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at XMLHttpRequest.y.onerror (file:///android_asset/www/js/app.min.js:112:195)
```

</details>

**Comment by nagyrobi** [comment]
Seems that the issue is that even without the reverse proxy, connected to port 8080 with plain http, the server wants to use https on the same port (in the headers)...

**Comment by NANISOREH** [comment]
I have the same exact issue, everything works except the Android app.
In my case, I use https, but I'm using my own reverse proxy instead of the caddy docker to do SSL termination and contacting the API with plain http, so I suspect it's the very same issue.

**Comment by nero120** [comment]
@NANISOREH could you post your log entries please just to confirm?

**Comment by NANISOREH** [comment]
Ofc! As far as I can tell, it's the same error.
Yesterday I checked logcat too via adb, and I think the system generated SSL errors whenever I tried to connect. Note that I'm using a self-signed certificate, but I signed it using my own Root CA and I added it to the system. Could it be that the app can't use the system CA store?
[xbs_log_20211210081128.txt](https://github.com/xbrowsersync/app/files/7691812/xbs_log_20211210081128.txt)

**Comment by nero120** [comment]
Thanks @NANISOREH, any chance you could try it with the latest [v1.6.0 beta](https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.27)?

**Comment by nero120** [comment]
@NANISOREH actually thinking about it some more, I'll enable the app to accept the user certificate store that should resolve your issue.

**Comment by nagyrobi** [comment]
In my experience HTTP should be usable. For example Home Assistant companion app is able to connect to Home Assistant server via both HTTP or HTTPS.

You can also test with WebView Test app from Google Play. You can open plain HTTP sites too.

I don't think that blocking plain HTTP is reasonable in such a way - there are lots of use cases when certain resources are only reachable via HTTP.

**Comment by nero120** [comment]
@nagyrobi ok I'll give it some thought.

**Comment by NANISOREH** [comment]
> @NANISOREH actually thinking about it some more, I'll enable the app to accept the user certificate store that should resolve your issue. Give me a couple of days.

That would be great!
Btw I tried the beta, no difference.

**Comment by nero120** [comment]
@nagyrobi @NANISOREH give this [beta release](https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.28) a try.

**Comment by NANISOREH** [comment]
Okay, now it can reach the API no problem, thanks for the fix!
Only bad news is syncing only works if I use the beta Firefox extension as well, and that means I would have to reinstall it on every restart until it gets signed if I understood correctly.

**Comment by nero120** [comment]
@NANISOREH great stuff thanks for checking! Won't have to use the beta for long, I'm hoping to release v1.6.0 this week!!

**Comment by NANISOREH** [comment]
The fix (at least for the issue I was having) is out in the beta, but I'm still waiting for the main release since I can only use it across all devices if they're on the same version, and the firefox beta extension is not usable (it uninstalls at every browser restart)
