### ISSUE TITLE
Constant sync error in MS Edge on Windows 11

### ISSUE THREAD

**Issue by drPRW1977** [xbrowsersync/app#394]
**Describe the issue you are experiencing**
When I add a new bookmark using the browser's bookmarking process, I get an error from xbrowsersync asking me to redo it and that the change was unsaved. When I add the bookmark using the extension's process, there is no issue. But using that avenue, I can't find the bookmark unless I search for it (requiring me to remember what it's called and/or which tags I used). EDIT: This does not happen on Chrome.

**How can the issue be reproduced?**
Steps to reproduce the behavior
1. Add a bookmark using MS Edge's add bookmark process (click the icon in the address bar).

**Screenshots**
Screenshot of error is here: https://1drv.ms/u/s!Agrjq8H63mhcovQCMYEgeixIqvu6BQ?e=wKWNph 

**Desktop browser**
Please complete the following information for all affected desktop browsers:
Microsoft Edge Version 100.0.1185.44 (Official build) (64-bit) although it has been happening for a while in earlier versions too
Windows 11 (22000.613)

**Application log**
Please include the logs from the affected clients:

<details>
<summary>Log entries</summary>

```
2022-04-17 19:14:53.312	[trace]	onCreated event detected
2022-04-17 19:14:54.340	[trace]	Sync 12gj6xp (push) queued
2022-04-17 19:14:54.593	[trace]	Processing sync 12gj6xp (0 in queue)
2022-04-17 19:14:54.613	[trace]	Sync 12gj6xp failed
2022-04-17 19:14:54.641	[error]	bookmarks.sync: [10111] XBookmarkNotFound	TypeError: Cannot read properties of undefined (reading '4') at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2555:41 at Array.reduce (<anonymous>) at Object.addNewInXBookmarks [as AddNewInXBookmarks] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2554:49) at Object.bookmarksCreated [as Created] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3844:26) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3555:55 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:154:326 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:52:3
2022-04-17 19:14:54.657	[trace]	{"bookmark":{"dateAdded":1650222893314,"index":23,"parentId":"15262","title":"Digital Downloads","url":"https://www.stjohns.edu/about/news/social-st-johns-university/digital-downloads","description":"","tags":null},"container":"[xbs] Toolbar","indexPath":[4,56,4,18,23],"type":1}
2022-04-17 19:14:54.675	[trace]	Sync 1nizt8d (pull) queued
2022-04-17 19:14:54.707	[trace]	Processing sync 1nizt8d (0 in queue)
2022-04-17 19:14:56.332	[trace]	Local population completed in 1.238s
2022-04-17 19:14:56.396	[trace]	Local sync data refreshed
2022-04-17 19:15:05.555	[trace]	onCreated event detected
2022-04-17 19:15:06.582	[trace]	Sync v6ugw6 (push) queued
2022-04-17 19:15:06.713	[trace]	Processing sync v6ugw6 (0 in queue)
2022-04-17 19:15:06.732	[trace]	Sync v6ugw6 failed
2022-04-17 19:15:06.745	[error]	bookmarks.sync: [10111] XBookmarkNotFound	TypeError: Cannot read properties of undefined (reading '4') at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2555:41 at Array.reduce (<anonymous>) at Object.addNewInXBookmarks [as AddNewInXBookmarks] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2554:49) at Object.bookmarksCreated [as Created] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3844:26) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3555:55 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:154:326 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:52:3
2022-04-17 19:15:06.761	[trace]	{"bookmark":{"dateAdded":1650222905553,"index":23,"parentId":"15729","title":"Digital Downloads","url":"https://www.stjohns.edu/about/news/social-st-johns-university/digital-downloads","description":"","tags":null},"container":"[xbs] Toolbar","indexPath":[4,56,4,18,23],"type":1}
2022-04-17 19:15:06.769	[trace]	Sync 5ew3k5 (pull) queued
2022-04-17 19:15:06.779	[trace]	Processing sync 5ew3k5 (0 in queue)
2022-04-17 19:15:08.023	[trace]	Local population completed in 0.889s
2022-04-17 19:15:08.087	[trace]	Local sync data refreshed
2022-04-17 19:15:15.678	[trace]	onCreated event detected
2022-04-17 19:15:16.694	[trace]	Sync 10l66wv (push) queued
2022-04-17 19:15:16.846	[trace]	Processing sync 10l66wv (0 in queue)
2022-04-17 19:15:16.864	[trace]	Sync 10l66wv failed
2022-04-17 19:15:16.869	[error]	bookmarks.sync: [10111] XBookmarkNotFound	TypeError: Cannot read properties of undefined (reading '4') at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2555:41 at Array.reduce (<anonymous>) at Object.addNewInXBookmarks [as AddNewInXBookmarks] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2554:49) at Object.bookmarksCreated [as Created] (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3844:26) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:3555:55 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:154:326 at Tg.completeTask (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:166:15) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:52:3
2022-04-17 19:15:16.881	[trace]	{"bookmark":{"dateAdded":1650222915676,"index":23,"parentId":"16195","title":"Digital Downloads","url":"https://www.stjohns.edu/about/news/social-st-johns-university/digital-downloads","description":"","tags":null},"container":"[xbs] Toolbar","indexPath":[4,56,4,18,23],"type":1}
2022-04-17 19:15:16.889	[trace]	Sync dpny0i (pull) queued
2022-04-17 19:15:16.894	[trace]	Processing sync dpny0i (0 in queue)
2022-04-17 19:15:18.208	[trace]	Local population completed in 0.955s
2022-04-17 19:15:18.267	[trace]	Local sync data refreshed
```

</details>

**Comment by derfel1989** [comment]
Same issue on Windows 10 MS Edge Version 100.0.1185.44 (Official Build) (64-bit).

![image](https://user-images.githubusercontent.com/46175778/164795924-24b2a945-0897-42d6-b1c3-9796b4bfe0be.png)

**Comment by nero120** [comment]
I think this issue may already be resolved, can you please try with the latest beta:

https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.59

**Do not use your "live" sync ID with a beta release, create a new sync after installing the beta. If you wish to have your existing bookmarks simply restore from a previous backup.**

**Comment by drPRW1977** [comment]
I downgraded to Windows 10 and I haven't had the issue again using Edge. I wonder if it's just a Windows 11 problem?

**Comment by nero120** [comment]
Do you get this issue on Chrome in Windows 11 also?

**Comment by drPRW1977** [comment]
> Do you get this issue on Chrome in Windows 11 also?

No, I have not had an issue with Chrome (although I don't use it regularly like I do Edge).

**Comment by UrmaGurd** [comment]
having this issue on Mac Chrome browser. Constantly getting this notification of sync error with local data changing. The bookmarks are correct though. 

I have a chain of syncing... Brave on Windows, Chrome on Windows, Chrome on Mac. First two work fine, the Mac one keeps showing this error. had to disable.

Running 1.5.2

**Comment by Bartek200219** [comment]
Same issue on Vivaldi 5.5.2805.38

**Comment by Mihaeru** [comment]
I just installed xBrowserSync and got the same error on Windows 11 on both, Chrome 111.0.5563.147 and Firefox 111.0.1. I haven't tried MS Edge so far. I installed both extensions from the official web stores.
Sync service is https://xbsapi.cgrx.de/

**Comment by natpicone** [comment]
👋 This issue has been identified as a duplicate of #456.

Please continue the discussion in the original issue so we can keep things organised.
Closing this one to reduce noise — thank you for reporting! 🙏
