### ISSUE TITLE
Connection to service lost

### ISSUE THREAD

**Issue by graphixillusion** [xbrowsersync/app#426]
Hi there. Since a couple of days i'm getting this notification (see the title of this issue) every time when i start chrome.  I'm using this server as service "https://api.xbrowsersync.org/" and it isn't offline. Here's the log:

```
2022-10-26 11:49:17.517	[trace]	Starting up
2022-10-26 11:49:17.875	[trace]	{"displayHelp":false,"displayOtherSyncsWarning":false,"displayUpdated":false,"lastUpdated":"2022-10-23T17:41:44.741Z","networkDisconnected":false,"syncEnabled":true,"syncId":"REMOVED","syncVersion":"1.5.2","appVersion":"1.5.2","platform":{"name":"chrome","version":"107.0.0","mobile":false,"os":"Windows 10"}}
2022-10-26 11:49:19.328	[error]		Error: [10001] HttpRequestFailed at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2389:42 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at m.$apply (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:155:35) at k (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:106:129) at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:111:206) at y.onerror (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:112:195)
2022-10-26 11:49:19.330	[trace]	Connection to API failed, retrying check for sync updates momentarily
2022-10-26 11:49:24.369	[error]		Error: [10001] HttpRequestFailed at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:2389:42 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:151:185) at m.$apply (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:155:35) at k (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:106:129) at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:111:206) at y.onerror (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/background.min.js:112:195)
2022-10-26 11:49:27.400	[error]		Error: [10001] HttpRequestFailed at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:1867:42 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:151:185) at m.$apply (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:155:35) at k (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:106:129) at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:111:206) at y.onerror (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:112:195)
```

**Comment by Bombarmil** [comment]
Hi there. Same happens to me too. I thought it was the extension so i reinstalled it but i get this notification regardless. Log says the same as yours so i dont post it here.

**Comment by brycewray** [comment]
Confirming report and timing given by @graphixillusion — seemed to start sometime on Monday, 2022-10-26 (U.S.). I didn’t notice it until after upgrading macOS to Ventura, so thought perhaps it was related to that until I opened the extension and tried https://api.xbrowsersync.org, which at least on Chrome returns: 

> This page isn’t working
> 
> api.xbrowsersync.org redirected you too many times.

**Comment by chowder3907** [comment]
same issue on 2 different PCs

**Comment by Zulgrib** [comment]
Was able to reproduce, doesn't matter the browser or host system.

**Comment by gqqjhffr** [comment]
Ditto

**Comment by Fdebriey** [comment]
Same problem since yesterday 26/10

**Comment by daservo** [comment]
Same problem. 
Nevertheless, status of `api.xbrowsersync.org` on [this](https://www.xbrowsersync.org/#download:~:text=Download%20APK-,Services,-Choose%20from%20one) page shows no problems.
I have switched to another service from the list, sync is working again.

**Comment by pedrofusc** [comment]
@daservo i can't access any links from xbrowsersync.

To which service do you change to make it work again?

**Comment by djwyman** [comment]
> @daservo i can't access any links from xbrowsersync.
> 
> To which service do you change to make it work again?

I went with https://xbrowsersync.freerangecloud.com

I actually had to use a VPN to be able to get on to the main site for some reason to even see a list of providers.

**Comment by robert-winkler** [comment]
Same problem here; on a new installation of Fedora with chromium, Firefox, and Opera.

The service is working, with temporal interruptions, on a Manjaro Linux and Android.

**Comment by Solomon1732** [comment]
How do I switch services? I tried to look in the documentation in the addon. I couldn't understand how to do it

**Comment by graphixillusion** [comment]
> How do I switch services? I tried to look in the documentation in the addon. I couldn't understand how to do it

You need to disable sync and start the sync again from the beginning. From there you can choose different services

**Comment by Solomon1732** [comment]
@graphixillusion Found it. I tried doing it, but it looks as if I lost the latest bookmarks I saved on my android. Any idea how I extract them? Or are they lost for all eternity?

**Comment by nero120** [comment]
I can access https://www.xbrowsersync.org/ and https://api.xbrowsersync.org/ fine from the UK without a VPN. I'm seeing some chatter indicating that some countries (such as Uruguay and Argentina) are unable to access the server that hosts xbrowsersync.org, though I have no idea why that might be the case!

**Comment by djwyman** [comment]
> I can access https://www.xbrowsersync.org/ and https://api.xbrowsersync.org/ fine from the UK without a VPN. I'm seeing some chatter indicating that some countries (such as Uruguay and Argentina) are unable to access the server that hosts xbrowsersync.org, though I have no idea why that might be the case!

I am located in the U.S. and am unable to access either sites without using a vpn.  I don't know if it is an ISP issue or what.

**Comment by daservo** [comment]
> @daservo i can't access any links from xbrowsersync.
> To which service do you change to make it work again?

https://xbrowsersync.servicesforfree.com/ is working for me.

**Comment by nero120** [comment]
> > I can access https://www.xbrowsersync.org/ and https://api.xbrowsersync.org/ fine from the UK without a VPN. I'm seeing some chatter indicating that some countries (such as Uruguay and Argentina) are unable to access the server that hosts xbrowsersync.org, though I have no idea why that might be the case!
> 
> I am located in the U.S. and am unable to access either sites without using a vpn. I don't know if it is an ISP issue or what.

What error are you seeing if you try to access www.xbrowsersync.org?

**Comment by nero120** [comment]
ping.pe can't see any issues connecting to the server from various countries:

https://tcp.ping.pe/206.189.114.140:443

**Comment by djwyman** [comment]
> > > I can access https://www.xbrowsersync.org/ and https://api.xbrowsersync.org/ fine from the UK without a VPN. I'm seeing some chatter indicating that some countries (such as Uruguay and Argentina) are unable to access the server that hosts xbrowsersync.org, though I have no idea why that might be the case!
> > 
> > 
> > I am located in the U.S. and am unable to access either sites without using a vpn. I don't know if it is an ISP issue or what.
> 
> What error are you seeing if you try to access https://www.xbrowsersync.org?

ERR_TOO_MANY_REDIRECTS on brave and edge 
on my phone ussafari using both cellular network and wifi too many redirects occurred

**Comment by nero120** [comment]
> ERR_TOO_MANY_REDIRECTS on brave and edge
on my phone using safari using both cellular network and wifi too many redirects occurred

Ok thanks, do you get the same if you visit https://www.xbrowsersync.org/privacypolicy?

**Comment by lionkmp** [comment]
I had the same problem but **when using ProtonVPN**. Note that Firefox also displays a message related to incorrect redirection (I don't have the exact English message). Both the "www" site and the "api" site has the same problem. If I disconnect from ProtonVPN and I use my own ISP network, it works.

**Comment by nero120** [comment]
I honestly have no idea why!

- What changed all of a sudden to start causing this a few weeks ago - the server configuration has not changed at all?
- Why does the server respond find from some IP ranges/countries but not others?

Confused.com!

**Comment by djwyman** [comment]
> > ERR_TOO_MANY_REDIRECTS on brave and edge
> > on my phone using safari using both cellular network and wifi too many redirects occurred
> 
> Ok thanks, do you get the same if you visit https://www.xbrowsersync.org/privacypolicy?
> 
> When I check server redirects for this URL using an online tool it's not reporting any issues:
> 
> https://kinsta.com/tools/redirect-checker/
> 
> ![image](https://user-images.githubusercontent.com/4236238/198718986-638d2761-7700-4ab8-9887-e70d467be1de.png)
> 
> Same for any other url on xbrowsersync.org

Yes I get the same thing for that one as well unless I turn on a VPN



> I have the same problem but **when using ProtonVPN**. Note that Firefox also displays a message related to incorrect redirection (I don't have the exact English message). Both the "www" site and the "api" site has the same problem. If I disconnect from ProtonVPN and I use my own ISP network, it works. (Sync does not work too.)

Proton VPN is what I am using to actually get through to the site so I don't know LoL.

**Comment by kainz** [comment]
Something's gone weird with your cloudflare protection/proxy config @nero120 .  The redirects are coming from cloudflare: 
curl -v -I https://www.xbrowsersync.org                                                                                                                                                                     k:
*   Trying 2606:4700:3035::ac43:a3ee:443...
* Connected to www.xbrowsersync.org (2606:4700:3035::ac43:a3ee) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Jun 17 00:00:00 2022 GMT
*  expire date: Jun 17 23:59:59 2023 GMT
*  subjectAltName: host "www.xbrowsersync.org" matched cert's "*.xbrowsersync.org"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* Using Stream ID: 1 (easy handle 0x5613faf7ae80)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> HEAD / HTTP/2
> Host: www.xbrowsersync.org
> user-agent: curl/7.81.0
> accept: */*
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 308 
HTTP/2 308 
< date: Fri, 28 Oct 2022 21:42:24 GMT
date: Fri, 28 Oct 2022 21:42:24 GMT
< location: https://www.xbrowsersync.org/
location: https://www.xbrowsersync.org/
< cf-cache-status: DYNAMIC
cf-cache-status: DYNAMIC
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=tpdhBC3dTxtKlUozayps6ehl5jWl%2FxTnis%2BSA5eXGLNgmTbe0ELfwowT%2Fsy3tOs2z1zjGKo8PbzZ%2F90gwn2PRjHIcTKrFzYJitC7NSlBCUBkNci87bazRIRecKhCaXm%2F76iEGdvISJquzey9VDyvfVkOLw%3D%3D"}],"group":"cf-nel","max_age":604800}
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=tpdhBC3dTxtKlUozayps6ehl5jWl%2FxTnis%2BSA5eXGLNgmTbe0ELfwowT%2Fsy3tOs2z1zjGKo8PbzZ%2F90gwn2PRjHIcTKrFzYJitC7NSlBCUBkNci87bazRIRecKhCaXm%2F76iEGdvISJquzey9VDyvfVkOLw%3D%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
server: cloudflare
< cf-ray: 7616d7507f3f2a09-ORD
cf-ray: 7616d7507f3f2a09-ORD
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

**Comment by nero120** [comment]
@kainz I've no idea how to read that! Any idea what I need to do to resolve the issue?

**Comment by kainz** [comment]
you'll probably need to check your cloudflare proxy setup for you domain on their platform.

**Comment by Tsee2** [comment]
Same problem: the service and www.xbrowsersync.org not available from Germany (different DSL and different DNS service). With VPN (swiss, GB, even with German IP) everthing is available. Maybe it is a IPv6-failure?

**Comment by hkluis** [comment]
From US AT&T, I can reach https://www.xbrowsersync.org/, but https://api.xbrowsersync.org/ returns ERR_TOO_MANY_REDIRECTS.

If I switch service to https://xbrowsersync.freerangecloud.com/, it doesn't recognize my credentials.  Is it because these public servers don't sync among each other?  If so, how do you who switch service get your bookmarks?

**Comment by kainz** [comment]
> If so, how do you who switch service get your bookmarks?

Export with the backup button, setup account on whatever target api instance, then import backup.

**Comment by graphixillusion** [comment]
> From US AT&T, I can reach https://www.xbrowsersync.org/, but https://api.xbrowsersync.org/ returns ERR_TOO_MANY_REDIRECTS.
> 
> If I switch service to https://xbrowsersync.freerangecloud.com/, it doesn't recognize my credentials. Is it because these public servers don't sync among each other? If so, how do you who switch service get your bookmarks?

but take attention becouse the import/export synced data is not equal to have all the bookmarks synced becouse of this issue. If you added something new into a browser/system with the faulty address, that data wasn't synced successfully. My advice is to take a backup of all the bookmarks into a system which is 100% up to date and then make the sync again.

**Comment by Nburnes** [comment]
Not sure what step did it, if individually or together, but I used a VPN to appear out of France (from US) and cleared cache in the Android app, and now my app is syncing to api.xbrowsersync.org again. This is working without VPN and through reboots. Tested by adding and removing some test links on laptop and in Android app.

**Comment by Tsee2** [comment]
In Germany everything seems to be going well again (at the moment)

**Comment by nero120** [comment]
Interesting. I'm just going to make a little change, can you see if it goes down again?

**Comment by nero120** [comment]
> Maybe the owner of the domain did something with his cloudflare's config which was the main problem of this issue.

I am the owner and no I did not make any change recently.

**Comment by Tsee2** [comment]
It is 19:35 Berlin time and the connection is still working.

**Comment by nero120** [comment]
Thanks guys, that means I have no idea what could of caused the issue, and why is suddenly resolved itself! I can only guess that this was a general cloudflare issue that they resolved behind the scenes.

**Comment by Bombarmil** [comment]
For me (and my family on 3 different computers in germany) it still isn't working. When I try to switch to https://api.xbrowsersync.org/ it tells me "Unable to connect to the service".

**Comment by mrusme** [comment]
I'm having the same issue. I have xbrowsersync running in Chrome and it successfully connects and syncs. When I try to set up XBS on Android however, I see the following errors in the Android app log:

```
2022-12-12 00:46:09.324	[trace]	Service url changed to: https://10.0.0.10:8443/api/v1
2022-12-12 00:46:09.466	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onabort (file:///android_asset/www/js/app.min.js:112:301)
2022-12-12 00:46:09.539	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onabort (file:///android_asset/www/js/app.min.js:112:301)
2022-12-12 00:46:15.587	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onabort (file:///android_asset/www/js/app.min.js:112:301)
2022-12-12 00:46:20.978	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onabort (file:///android_asset/www/js/app.min.js:112:301)
2022-12-12 00:46:24.374	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onabort (file:///android_asset/www/js/app.min.js:112:301)
2022-12-12 00:46:28.903	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onabort (file:///android_asset/www/js/app.min.js:112:301)
2022-12-12 00:46:32.190	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onabort (file:///android_asset/www/js/app.min.js:112:301)
2022-12-12 00:46:33.113	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onabort (file:///android_asset/www/js/app.min.js:112:301)
2022-12-12 00:46:37.588	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onabort (file:///android_asset/www/js/app.min.js:112:301)
2022-12-12 00:46:44.539	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onabort (file:///android_asset/www/js/app.min.js:112:301)
2022-12-12 00:46:46.019	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onabort (file:///android_asset/www/js/app.min.js:112:301)
```

I'm using the latest version available on F-Droid.

**Comment by kainz** [comment]
This still occurs for me with the xbrowsersync app, as well as the xbrowsersync addon on kiwi mobile. This is the application log on the xbrowsersync mobile app, version 1.5.2:
```
2022-12-23 02:40:08.667	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-12-23 02:40:15.149	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-12-23 02:40:19.531	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
```

A fresh sync on an alternate desktop profile but the same sync account using a freshly installed firefox instance does work.

Using a fresh sync on a non api.browsersync.org endpoint (tested with the `https://xbrowsersync.freerangecloud.com/` endpoint works) works on my test desktop and mobile devices as well, so the cloudflare protection on api.xbrowsersync.org is probably breaking the api of the mobile apps, still.
