### ISSUE TITLE
I can't use the extension on the kiwi browser on mobile

### ISSUE THREAD

**Issue by Raulking86** [xbrowsersync/app#437]
**Describe the issue you are experiencing**
A clear and concise description of your issue:

**How can the issue be reproduced?**

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Desktop browser**
Please complete the following information for all affected desktop browsers:

- OS: [e.g. Win10]
- Browser [e.g. Chrome, Firefox]
- Version [e.g. v1.5.0]

**Mobile device**
Please complete the following information for all affected mobile devices:

- Device: [e.g. Samsung Galaxy S10]
- OS: [e.g. Android 9 Pie]
- Version [e.g. v1.5.0]

**Application log**
Please include the logs from the affected clients:

<details>
<summary>Log entries</summary>

```
Download the Application log from the Settings panel and paste the contents here.
```

</details>

**Comment by kainz** [comment]
This also occurs for me with the xbrowsersync app, as well as the xbrowsersync addon on kiwi mobile. This is the application log on the xbrowsersync mobile app, version 1.5.2:
```
2022-12-23 02:40:08.667	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-12-23 02:40:15.149	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
2022-12-23 02:40:19.531	[error]		Error: [10001] HttpRequestFailed at file:///android_asset/www/js/app.min.js:2461:38 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onerror (file:///android_asset/www/js/app.min.js:112:195)
```

A fresh sync on an alternate desktop profile but the same sync account using a freshly installed firefox instance does work.

Using a fresh sync on a non api.browsersync.org endpoint (tested with the `https://xbrowsersync.freerangecloud.com/` endpoint works) works on my test desktop and mobile devices as well, so the cloudflare protection on api.xbrowsersync.org is probably breaking the api of the mobile apps, still, same as #426 .
