### ISSUE TITLE
Duplication of top level folders (visible in browser bookmark manager only)

### ISSUE THREAD

**Issue by lionkmp** [xbrowsersync/app#441]
**Describe the issue you are experiencing**

I'm using xBrowserSync (1.7 beta) in 3 Linux systems on the same PC. 2 runs Firefox ESR, 1 runs LibreWolf (a variation of Firefox).

Sometimes bookmarks get duplicated on sync. The result looks as: Toolbar bookmarks are duplicated. Top level folders in my Bookmarks are duplicated (they include all their content).

BUT: when I use xBrowserSync to view bookmarks, nothing is duplicated there (currently, however I think it was different before or maybe after some more duplication).

Now I noticed this happened when I rebooted the PC into another Linux. - But I'll watch in the future update if this is not related.

**How can the issue be reproduced?**

1. Use 3 Linuxes and try to sync with xBrowserSync

**Screenshots**

Here you can see some of the duplication on Toolbar (the first item is also duplicated but appears as last). But nothing is duplicated in XBS GUI. 

![xbs](https://user-images.githubusercontent.com/5088657/210645995-3b152a25-8b17-482b-8116-48b3f676a937.jpg)

Since I don't know how this will go on with in the future, I usually reload a backup in this case. (By booting back to previous Linux after removing ETH cable, making backup, booting back to the problem and loading backup.)

**Desktop browser**

- OS: Ubuntu Linux, Mageia Linux, AntiX Linux
- Browser Firefox ESR latest, LibreWolf latest
- Version XBS 1.7.0 beta 47

**Mobile device**

n/a

**Application log**

These were the last lines before I shut down Ubuntu/LibreWolf today around 20:00  (where bookmarks looked OK)

<details>
<summary>Log entries</summary>

```
2023-01-04 14:26:11.194	[trace]	Starting up
2023-01-04 14:26:11.394	[trace]	Starting up
2023-01-04 14:26:11.511	[trace]	{"lastUpdated":"2023-01-02T21:55:50.490Z","syncId":"###","appVersion":"1.7.0-beta.47","checkForAppUpdates":true,"currentLocale":"hu","platform":{"name":"firefox","version":"108.0.0","os":"Linux","type":"browser"},"serviceUrl":"https://api.xbrowsersync.org","syncBookmarksToolbar":true,"syncEnabled":true,"syncVersion":"1.7.0"}
2023-01-04 14:26:11.611	[trace]	{"lastUpdated":"2023-01-02T21:55:50.490Z","syncId":"###","appVersion":"1.7.0-beta.47","checkForAppUpdates":true,"currentLocale":"hu","platform":{"name":"firefox","version":"108.0.0","os":"Linux","type":"browser"},"serviceUrl":"https://api.xbrowsersync.org","syncBookmarksToolbar":true,"syncEnabled":true,"syncVersion":"1.7.0"}
2023-01-04 16:57:07.209	[trace]	Starting up
2023-01-04 16:57:07.409	[trace]	Starting up
2023-01-04 16:57:07.509	[trace]	{"lastUpdated":"2023-01-02T21:55:50.490Z","syncId":"###","appVersion":"1.7.0-beta.47","checkForAppUpdates":true,"currentLocale":"hu","platform":{"name":"firefox","version":"108.0.0","os":"Linux","type":"browser"},"serviceUrl":"https://api.xbrowsersync.org","syncBookmarksToolbar":true,"syncEnabled":true,"syncVersion":"1.7.0"}
2023-01-04 16:57:07.559	[trace]	{"lastUpdated":"2023-01-02T21:55:50.490Z","syncId":"###","appVersion":"1.7.0-beta.47","checkForAppUpdates":true,"currentLocale":"hu","platform":{"name":"firefox","version":"108.0.0","os":"Linux","type":"browser"},"serviceUrl":"https://api.xbrowsersync.org","syncBookmarksToolbar":true,"syncEnabled":true,"syncVersion":"1.7.0"}
```
</details>

That time I immediately started the AntiX Linux/Firefox ESR. Duplication was visible:

(The beginning of the log 2 days ago might be that I reloaded the backup due to same problem.)

<details>
<summary>Log entries</summary>

```
2023-01-02 09:55:25.040	[trace]	Processing sync 44kael (18 waiting in queue)
2023-01-02 09:55:25.245	[trace]	Processing sync 1wsihtz (17 waiting in queue)
2023-01-02 09:55:25.455	[trace]	Processing sync t6gcqd (16 waiting in queue)
2023-01-02 09:55:25.670	[trace]	Processing sync 1az54n5 (15 waiting in queue)
2023-01-02 09:55:25.876	[trace]	Processing sync g97gfy (14 waiting in queue)
2023-01-02 09:55:26.075	[trace]	Processing sync eoi5ok (13 waiting in queue)
2023-01-02 09:55:26.285	[trace]	Processing sync nsbb29 (12 waiting in queue)
2023-01-02 09:55:26.498	[trace]	Processing sync fanycs (11 waiting in queue)
2023-01-02 09:55:26.710	[trace]	Processing sync 1w5a127 (10 waiting in queue)
2023-01-02 09:55:26.932	[trace]	Processing sync 1v1fn (9 waiting in queue)
2023-01-02 09:55:27.136	[trace]	Processing sync k9wjh8 (8 waiting in queue)
2023-01-02 09:55:27.341	[trace]	Processing sync c8cy0g (7 waiting in queue)
2023-01-02 09:55:27.543	[trace]	Processing sync 1pskrnv (6 waiting in queue)
2023-01-02 09:55:27.786	[trace]	Processing sync xkgerf (5 waiting in queue)
2023-01-02 09:55:27.999	[trace]	Processing sync 1agl6gg (4 waiting in queue)
2023-01-02 09:55:28.226	[trace]	Processing sync vlwm55 (3 waiting in queue)
2023-01-02 09:55:28.446	[trace]	Processing sync 6m1hpg (2 waiting in queue)
2023-01-02 09:55:28.774	[trace]	Processing sync dbape4 (1 waiting in queue)
2023-01-02 09:55:29.017	[trace]	Processing sync f088ar (0 waiting in queue)
2023-01-02 09:55:30.047	[trace]	Remote bookmarks updated at 2023-01-02T09:55:30.000Z
2023-01-04 20:04:39.737	[trace]	Starting up
2023-01-04 20:04:40.123	[trace]	Starting up
2023-01-04 20:04:40.157	[trace]	{"lastUpdated":"2023-01-02T09:55:30.000Z","syncId":"###","appVersion":"1.7.0-beta.47","checkForAppUpdates":true,"currentLocale":"en-US","platform":{"name":"firefox","version":"102.0.0","os":"Linux","type":"browser"},"serviceUrl":"https://api.xbrowsersync.org","syncBookmarksToolbar":true,"syncEnabled":true,"syncVersion":"1.7.0"}
2023-01-04 20:04:40.168	[trace]	{"lastUpdated":"2023-01-02T09:55:30.000Z","syncId":"###","appVersion":"1.7.0-beta.47","checkForAppUpdates":true,"currentLocale":"en-US","platform":{"name":"firefox","version":"102.0.0","os":"Linux","type":"browser"},"serviceUrl":"https://api.xbrowsersync.org","syncBookmarksToolbar":true,"syncEnabled":true,"syncVersion":"1.7.0"}
2023-01-04 20:04:46.208	[trace]	Updates available, local:2023-01-02T09:55:30.000Z remote:2023-01-02T21:55:50.490Z
2023-01-04 20:04:46.262	[trace]	Sync dsxjfy (LOCAL) queued
2023-01-04 20:04:46.274	[trace]	Updates available, local:2023-01-02T09:55:30.000Z remote:2023-01-02T21:55:50.490Z
2023-01-04 20:04:46.286	[trace]	Sync 1ytuxer (LOCAL) queued
2023-01-04 20:04:46.298	[trace]	Processing sync dsxjfy (1 waiting in queue)
2023-01-04 20:04:46.318	[trace]	Processing sync 1ytuxer (0 waiting in queue)
2023-01-04 20:05:50.789	[trace]	Waiting for syncs to finish...
2023-01-04 20:05:57.538	[trace]	803 bookmarks populated in 63.967s
2023-01-04 20:05:57.572	[trace]	803 bookmarks populated in 62.862s
2023-01-04 20:05:57.939	[warn]	Sync 1ytuxer failed
2023-01-04 20:05:58.012	[error]	Error (SyncFailedError): syncedBookmarks[index] is undefined at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:125:24) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:123:29) at browser.bookmarks.getSubTree(otherBookmarksId).then( (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:177:20)
2023-01-04 20:05:58.086	[warn]	Sync 1ytuxer failed
2023-01-04 20:05:58.099	[error]	Error (SyncFailedError): syncedBookmarks[index] is undefined at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:125:24) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:123:29) at browser.bookmarks.getSubTree(otherBookmarksId).then( (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:177:20)
2023-01-04 20:05:58.835	[trace]	Syncs finished, resuming
2023-01-04 20:09:02.573	[trace]	Updates available, local:2023-01-02T09:55:30.000Z remote:2023-01-02T21:55:50.490Z
```

</details>

Maybe the fact that it starts 2 sync and reports 803 bookmarks populated in **two lines**, that indicates something to you?

I'll add more info if I notice a pattern or something.

**Comment by lionkmp** [comment]
This problem solved itself today while I was writing this bug report!

Maybe I should just wait?? I'll report back if this always fixes itself.

(But something still needs to be fixed to avoid this confusion. ;-) )

Here is the log after the above lines:

<details>
<summary>Log entries</summary>

```
2023-01-04 20:09:02.573	[trace]	Updates available, local:2023-01-02T09:55:30.000Z remote:2023-01-02T21:55:50.490Z
2023-01-04 20:09:23.395	[trace]	Downloaded file /home3/ubuntu_home/lion/backup/xbs_log_20230104210915.txt
2023-01-04 20:29:55.014	[trace]	Starting up
2023-01-04 20:29:55.409	[trace]	Starting up
2023-01-04 20:29:55.446	[trace]	{"lastUpdated":"2023-01-02T09:55:30.000Z","syncId":"###","appVersion":"1.7.0-beta.47","checkForAppUpdates":true,"currentLocale":"en-US","platform":{"name":"firefox","version":"102.0.0","os":"Linux","type":"browser"},"serviceUrl":"https://api.xbrowsersync.org","syncBookmarksToolbar":true,"syncEnabled":true,"syncVersion":"1.7.0"}
2023-01-04 20:29:55.479	[trace]	{"lastUpdated":"2023-01-02T09:55:30.000Z","syncId":"###","appVersion":"1.7.0-beta.47","checkForAppUpdates":true,"currentLocale":"en-US","platform":{"name":"firefox","version":"102.0.0","os":"Linux","type":"browser"},"serviceUrl":"https://api.xbrowsersync.org","syncBookmarksToolbar":true,"syncEnabled":true,"syncVersion":"1.7.0"}
2023-01-04 20:30:01.753	[trace]	Updates available, local:2023-01-02T09:55:30.000Z remote:2023-01-04T20:27:17.040Z
2023-01-04 20:30:01.880	[trace]	Sync ba3uke (LOCAL) queued
2023-01-04 20:30:01.892	[trace]	Updates available, local:2023-01-02T09:55:30.000Z remote:2023-01-04T20:27:17.040Z
2023-01-04 20:30:01.903	[trace]	Sync 12sgun9 (LOCAL) queued
2023-01-04 20:30:02.105	[trace]	Processing sync ba3uke (1 waiting in queue)
2023-01-04 20:30:02.122	[trace]	Processing sync 12sgun9 (0 waiting in queue)
2023-01-04 20:30:09.295	[trace]	Waiting for syncs to finish...
2023-01-04 20:30:44.481	[trace]	Waiting for syncs to finish...
2023-01-04 20:30:59.618	[trace]	Waiting for syncs to finish...
2023-01-04 20:31:15.203	[trace]	804 bookmarks populated in 57.935s
2023-01-04 20:31:15.291	[trace]	804 bookmarks populated in 57.678s
2023-01-04 20:31:15.657	[warn]	Sync 12sgun9 failed
2023-01-04 20:31:15.733	[error]	Error (SyncFailedError): syncedBookmarks[index] is undefined at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:125:24) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:123:29) at browser.bookmarks.getSubTree(otherBookmarksId).then( (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:177:20)
2023-01-04 20:31:15.809	[warn]	Sync 12sgun9 failed
2023-01-04 20:31:15.823	[error]	Error (SyncFailedError): syncedBookmarks[index] is undefined at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:125:24) at mapIds (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:123:29) at browser.bookmarks.getSubTree(otherBookmarksId).then( (webpack://xbrowsersync-app/src/modules/webext/shared/webext-bookmark/webext-bookmark.service.ts:177:20)
2023-01-04 20:31:15.942	[error]	Possibly unhandled rejection: {}TypeError (TypeError): errors[err.message] is not a constructor at angular.isUndefined (webpack://xbrowsersync-app/src/modules/webext/shared/webext-platform/webext-platform.service.ts:340:31)
2023-01-04 20:38:48.210	[trace]	Updates available, local:2023-01-02T09:55:30.000Z remote:2023-01-04T20:27:17.040Z
2023-01-04 20:44:05.265	[trace]	Updates available, local:2023-01-02T09:55:30.000Z remote:2023-01-04T20:27:17.040Z
2023-01-04 20:46:16.132	[trace]	Updates available, local:2023-01-02T09:55:30.000Z remote:2023-01-04T20:27:17.040Z
2023-01-04 20:46:16.170	[trace]	Sync di6log (LOCAL) queued
2023-01-04 20:46:16.185	[trace]	Processing sync di6log (0 waiting in queue)
2023-01-04 20:47:01.043	[trace]	804 bookmarks populated in 39.167s
2023-01-04 20:47:01.304	[trace]	No changes made, skipping remote update.
```
</details>
