### ISSUE TITLE
Kiwi on Android won't sync

### ISSUE THREAD

**Issue by plug-it-in** [xbrowsersync/app#452]
**Describe the issue you are experiencing**
Initia sync on Kiwi browser.  Sync starts spinning goes for an age and then displays a message something went wrong

**How can the issue be reproduced?**
Install kiwi browser and try to sync

**Mobile device**
Please complete the following information for all affected mobile devices:

- Device:  Samsung Galaxy tab s6
- OS: Android Version 13

**Application log**
Please include the logs from the affected clients:

<details>
<summary>Log entries</summary>
V2023-04-30 15:13:45.652	[warn]	Missing container: other bookmarks
2023-04-30 15:13:45.661	[warn]	Missing container: toolbar bookmarks
2023-04-30 15:15:04.350	[error]		Error: Could not find an active window. at checkForApiError (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:4033:19) at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:3954:32
2023-04-30 15:19:11.760	[trace]	Sync 7jkj3q (pull) queued
2023-04-30 15:19:11.773	[trace]	Processing sync 7jkj3q (0 in queue)
2023-04-30 15:19:12.102	[warn]	Missing container: other bookmarks
2023-04-30 15:19:12.111	[warn]	Missing container: toolbar bookmarks
2023-04-30 15:19:12.116	[trace]	Sync 7jkj3q failed
2023-04-30 15:19:12.122	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2023-04-30 15:19:12.126	[trace]	Sync ej4qha (pull) queued
2023-04-30 15:19:12.130	[trace]	Processing sync ej4qha (0 in queue)
2023-04-30 15:19:12.207	[warn]	Missing container: other bookmarks
2023-04-30 15:19:12.214	[warn]	Missing container: toolbar bookmarks
2023-04-30 15:19:12.222	[trace]	Sync ej4qha failed
2023-04-30 15:19:12.226	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
</details>

**Comment by ddzzhen** [comment]
Same problem.
