### ISSUE TITLE
Syncing is not possible using MS Edge browser

### ISSUE THREAD

**Issue by gaoran1209** [xbrowsersync/app#456]
**The problem I am having**.
Syncing is not possible using MS Edge browser

**Steps to reproduce the behavior:

1. Go to the edge browser
2. Click on the xbrowsersync plugin
3. enter id, password and click sync button
4. The interface is always in the "syncing" state and bookmarks cannot be synced

**Screenshot**
![image](https://github.com/xbrowsersync/app/assets/15261543/838c3b6d-4490-4e08-9b3d-e2f1632fb999)
![image](https://github.com/xbrowsersync/app/assets/15261543/b8de842d-6eac-4936-8469-8b9fe8419068)

**Desktop Browsers**
- OS: MBP macOS Ventura 13.4.
- Browser:Microsoft Edge 
- Version: 112.0.1722.58 (official version) (arm64)

**Application logs**

2023-05-26 08:02:51.632	[warn]	Missing container: other bookmarks
2023-05-26 08:09:38.379	[error]		Error: [10106] NoDataFound at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:1884:38 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:151:185) at m.$apply (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:155:35) at k (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:106:129) at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:111:206) at y.onload (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:112:125)
2023-05-26 08:09:55.708	[trace]	Service url changed to: https://xbrowsersync.freerangecloud.com
2023-05-26 08:10:05.511	[trace]	Sync qaujsi (pull) queued
2023-05-26 08:10:05.513	[trace]	Processing sync qaujsi (0 in queue)
2023-05-26 08:10:06.082	[warn]	Missing container: other bookmarks
2023-05-26 08:10:06.084	[trace]	Sync qaujsi failed
2023-05-26 08:10:06.085	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2023-05-26 08:10:06.085	[trace]	Sync 1e8tulo (pull) queued
2023-05-26 08:10:06.086	[trace]	Processing sync 1e8tulo (0 in queue)
2023-05-26 08:10:06.485	[warn]	Missing container: other bookmarks
2023-05-26 08:10:06.486	[trace]	Sync 1e8tulo failed
2023-05-26 08:10:06.487	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2023-05-26 08:13:12.880	[trace]	Sync 1cwz0no (pull) queued
2023-05-26 08:13:12.880	[trace]	Processing sync 1cwz0no (0 in queue)
2023-05-26 08:13:13.582	[warn]	Missing container: other bookmarks
2023-05-26 08:13:13.584	[trace]	Sync 1cwz0no failed
2023-05-26 08:13:13.584	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2023-05-26 08:13:13.585	[trace]	Sync ok3s7q (pull) queued
2023-05-26 08:13:13.586	[trace]	Processing sync ok3s7q (0 in queue)
2023-05-26 08:13:14.033	[warn]	Missing container: other bookmarks
2023-05-26 08:13:14.034	[trace]	Sync ok3s7q failed
2023-05-26 08:13:14.034	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2023-05-26 08:14:25.589	[trace]	onCreated event detected
2023-05-26 08:14:25.637	[trace]	onChanged event detected
2023-05-26 08:14:25.638	[trace]	onCreated event detected
2023-05-26 08:14:25.639	[trace]	onChanged event detected
2023-05-26 08:14:25.639	[trace]	onCreated event detected
2023-05-26 08:14:25.640	[trace]	onChanged event detected
2023-05-26 08:14:25.648	[trace]	onCreated event detected
2023-05-26 08:14:25.649	[trace]	onCreated event detected
2023-05-26 08:14:25.649	[trace]	onChanged event detected
2023-05-26 08:14:25.650	[trace]	onCreated event detected
2023-05-26 08:14:25.651	[trace]	onChanged event detected
2023-05-26 08:14:25.651	[trace]	onCreated event detected
2023-05-26 08:14:25.652	[trace]	onChanged event detected
2023-05-26 08:14:25.652	[trace]	onCreated event detected
2023-05-26 08:14:25.653	[trace]	onChanged event detected
2023-05-26 08:14:25.653	[trace]	onCreated event detected
2023-05-26 08:14:25.654	[trace]	onChanged event detected
2023-05-26 08:14:25.654	[trace]	onCreated event detected
2023-05-26 08:14:25.655	[trace]	onChanged event detected
2023-05-26 08:14:25.655	[trace]	onCreated event detected
2023-05-26 08:14:25.656	[trace]	onChanged event detected
2023-05-26 08:14:25.656	[trace]	onCreated event detected
2023-05-26 08:14:25.657	[trace]	onChanged event detected
2023-05-26 08:14:25.657	[trace]	onCreated event detected
2023-05-26 08:14:25.658	[trace]	onChanged event detected
2023-05-26 08:14:25.658	[trace]	onCreated event detected
2023-05-26 08:14:25.659	[trace]	onChanged event detected
2023-05-26 08:14:25.659	[trace]	onCreated event detected
2023-05-26 08:14:25.660	[trace]	onChanged event detected
2023-05-26 08:14:25.660	[trace]	onCreated event detected
2023-05-26 08:14:25.661	[trace]	onChanged event detected
2023-05-26 08:14:25.662	[trace]	onCreated event detected
2023-05-26 08:14:25.662	[trace]	onChanged event detected
2023-05-26 08:14:25.663	[trace]	onCreated event detected
2023-05-26 08:14:25.663	[trace]	onChanged event detected
2023-05-26 08:14:25.664	[trace]	onCreated event detected
2023-05-26 08:14:25.664	[trace]	onCreated event detected
2023-05-26 08:14:25.665	[trace]	onChanged event detected
2023-05-26 08:14:25.665	[trace]	onCreated event detected
2023-05-26 08:14:25.665	[trace]	onChanged event detected
2023-05-26 08:14:25.666	[trace]	onCreated event detected
2023-05-26 08:14:25.667	[trace]	onChanged event detected
...
2023-05-26 08:14:26.407	[trace]	onChanged event detected
2023-05-26 08:14:26.731	[trace]	Sync 1ljbici (push) queued
2023-05-26 08:14:27.790	[trace]	Sync 1kburgr (push) queued
2023-05-26 08:14:27.921	[trace]	Sync 1fzy5zj (push) queued
2023-05-26 08:14:27.923	[trace]	Sync 1w4aj1p (push) queued
2023-05-26 08:14:27.924	[trace]	Sync 1y344rp (push) queued
2023-05-26 08:14:27.927	[trace]	Sync 1b1ro2b (push) queued
2023-05-26 08:14:27.929	[trace]	Sync 11nupoc (push) queued
2023-05-26 08:14:27.930	[trace]	Sync 13wo096 (push) queued
2023-05-26 08:14:27.932	[trace]	Sync 1l8n5w7 (push) queued
2023-05-26 08:14:27.934	[trace]	Sync hvneg (push) queued
2023-05-26 08:14:27.935	[trace]	Sync 1ck6tvb (push) queued
2023-05-26 08:14:27.937	[trace]	Sync 137napa (push) queued
2023-05-26 08:14:27.938	[trace]	Sync cbe83p (push) queued
2023-05-26 08:14:27.940	[trace]	Sync 1y5hd35 (push) queued
2023-05-26 08:14:27.942	[trace]	Sync w63h04 (push) queued
2023-05-26 08:14:27.943	[trace]	Sync 1rihvyh (push) queued
2023-05-26 08:14:27.945	[trace]	Sync 1wvikf5 (push) queued
2023-05-26 08:14:27.947	[trace]	Sync x86gl (push) queued
2023-05-26 08:14:27.948	[trace]	Sync 1mqpkhp (push) queued
2023-05-26 08:14:27.950	[trace]	Sync u6s99r (push) queued
2023-05-26 08:14:27.952	[trace]	Sync 1j89mc1 (push) queued
2023-05-26 08:14:27.953	[trace]	Sync rqw4tl (push) queued
2023-05-26 08:14:27.955	[trace]	Sync 166hqnv (push) queued

2023-05-26 08:14:28.497	[trace]	Sync 96c39t (push) queued
2023-05-26 08:14:28.499	[trace]	Sync 1nuo3hr (push) queued
2023-05-26 08:14:28.501	[trace]	Sync 1pu9bud (push) queued
...
2023-05-26 08:14:28.837	[trace]	Sync e9iogl (push) queued
2023-05-26 08:14:28.840	[trace]	Sync 166yhqy (push) queued
2023-05-26 08:14:28.842	[trace]	Sync 12eesss (push) queued
2023-05-26 08:14:28.844	[trace]	Sync yln0nt (push) queued
2023-05-26 08:14:28.847	[trace]	Sync flr4au (push) queued
2023-05-26 08:14:28.849	[warn]	Missing container: other bookmarks
2023-05-26 08:14:28.852	[warn]	Missing container: other bookmarks
2023-05-26 08:14:28.854	[warn]	Missing container: other bookmarks
...
2023-05-26 08:14:29.015	[warn]	Missing container: other bookmarks
2023-05-26 08:14:29.017	[warn]	Missing container: other bookmarks
2023-05-26 08:14:29.020	[warn]	Missing container: other bookmarks
2023-05-26 08:14:29.023	[trace]	Sync 1a0bpk7 (push) queued
2023-05-26 08:14:29.026	[trace]	Sync ec5s19 (push) queued
2023-05-26 08:14:29.029	[trace]	Sync j03jy (push) queued
2023-05-26 08:14:29.032	[trace]	Sync 1hz217c (push) queued
2023-05-26 08:14:29.036	[trace]	Sync iumk3j (push) queued
2023-05-26 08:14:29.039	[trace]	Sync 1sg1wo4 (push) queued
...
2023-05-26 08:14:29.845	[trace]	Sync b0aujh (push) queued
2023-05-26 08:14:29.849	[trace]	Sync hpsw2d (push) queued
2023-05-26 08:14:29.852	[trace]	Sync 1730qtk (push) queued
2023-05-26 08:14:29.855	[warn]	Missing container: other bookmarks
2023-05-26 08:14:29.860	[warn]	Missing container: other bookmarks
2023-05-26 08:14:29.863	[warn]	Missing container: other bookmarks
2023-05-26 08:14:29.867	[warn]	Missing container: other bookmarks
...
2023-05-26 08:14:32.389	[warn]	Missing container: other bookmarks
2023-05-26 08:14:32.394	[warn]	Missing container: other bookmarks
2023-05-26 08:14:32.399	[warn]	Missing container: other bookmarks
2023-05-26 08:14:32.405	[warn]	Missing container: other bookmarks
2023-05-26 08:14:32.410	[warn]	Missing container: other bookmarks
2023-05-26 08:14:32.415	[warn]	Missing container: other bookmarks
2023-05-26 08:14:32.422	[warn]	Missing container: other bookmarks
2023-05-26 08:18:55.713	[trace]	Waiting for syncs to finish...
2023-05-26 08:18:58.389	[trace]	Cancelling sync
2023-05-26 08:18:58.396	[trace]	Sync 1rpnb6s (cancel) queued
2023-05-26 08:18:58.413	[trace]	Processing sync 1rpnb6s (0 in queue)
2023-05-26 08:19:10.710	[trace]	Sync 10xp02t (pull) queued
2023-05-26 08:19:10.725	[trace]	Processing sync 10xp02t (0 in queue)
2023-05-26 08:19:11.266	[warn]	Missing container: other bookmarks
2023-05-26 08:19:11.275	[trace]	Sync 10xp02t failed
2023-05-26 08:19:11.283	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2023-05-26 08:19:11.289	[trace]	Sync 1e1xaq7 (pull) queued
2023-05-26 08:19:11.295	[trace]	Processing sync 1e1xaq7 (0 in queue)
2023-05-26 08:19:11.681	[warn]	Missing container: other bookmarks
2023-05-26 08:19:11.693	[trace]	Sync 1e1xaq7 failed
2023-05-26 08:19:11.701	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2023-05-26 08:21:30.144	[trace]	Sync 1o031a0 (pull) queued
2023-05-26 08:21:30.153	[trace]	Processing sync 1o031a0 (0 in queue)
2023-05-26 08:21:30.784	[warn]	Missing container: other bookmarks
2023-05-26 08:21:30.794	[trace]	Sync 1o031a0 failed
2023-05-26 08:21:30.803	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2023-05-26 08:21:30.810	[trace]	Sync pijddc (pull) queued
2023-05-26 08:21:30.817	[trace]	Processing sync pijddc (0 in queue)
2023-05-26 08:21:31.210	[warn]	Missing container: other bookmarks
2023-05-26 08:21:31.222	[trace]	Sync pijddc failed
2023-05-26 08:21:31.235	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2023-05-26 08:21:46.479	[error]		Error: [10006] DailyNewSyncLimitReached at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:1818:38 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:151:185) at m.$apply (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:155:35) at k (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:106:129) at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:111:206) at y.onload (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:112:125)
2023-05-26 08:22:01.597	[error]		Error: [10006] DailyNewSyncLimitReached at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:1818:38 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:151:185) at m.$apply (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:155:35) at k (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:106:129) at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:111:206) at y.onload (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:112:125)
2023-05-26 08:22:31.334	[trace]	Service url changed to: https://xbs.andrewkdinh.com
2023-05-26 08:22:41.586	[error]		Error: [10300] InvalidService at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:1818:38 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:151:185) at m.$apply (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:155:35) at k (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:106:129) at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:111:206) at y.onload (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:112:125)
2023-05-26 08:22:45.040	[error]		Error: [10300] InvalidService at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:1818:38 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:151:185) at m.$apply (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:155:35) at k (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:106:129) at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:111:206) at y.onload (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:112:125)
2023-05-26 08:22:46.473	[error]		Error: [10300] InvalidService at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:1818:38 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:151:185) at m.$apply (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:155:35) at k (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:106:129) at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:111:206) at y.onload (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:112:125)
2023-05-26 08:22:47.697	[error]		Error: [10300] InvalidService at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:1818:38 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:151:185) at m.$apply (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:155:35) at k (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:106:129) at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:111:206) at y.onload (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:112:125)
2023-05-26 08:22:48.845	[error]		Error: [10300] InvalidService at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:1818:38 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:151:185) at m.$apply (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:155:35) at k (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:106:129) at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:111:206) at y.onload (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:112:125)
2023-05-26 08:22:50.037	[error]		Error: [10300] InvalidService at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:1818:38 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:151:185) at m.$apply (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:155:35) at k (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:106:129) at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:111:206) at y.onload (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:112:125)
2023-05-26 08:23:00.048	[trace]	Service url changed to: https://api.xbrowsersync.org
2023-05-26 08:23:08.043	[trace]	Sync 1l7w7vu (push) queued
2023-05-26 08:23:08.050	[trace]	Processing sync 1l7w7vu (0 in queue)
2023-05-26 08:23:08.066	[warn]	Missing container: other bookmarks
2023-05-26 08:23:08.071	[trace]	Sync 1l7w7vu failed
2023-05-26 08:23:08.077	[error]	bookmarks.sync: [10113] LocalContainerNotFound
2023-05-26 08:23:33.104	[trace]	onMoved event detected
2023-05-26 08:23:34.123	[trace]	Sync elwk3u (push) queued
2023-05-26 08:23:34.137	[warn]	Missing container: other bookmarks
2023-05-26 08:23:34.155	[warn]	Missing container: other bookmarks
2023-05-26 08:23:44.768	[trace]	onMoved event detected
2023-05-26 08:23:45.784	[trace]	Sync 4w277n (push) queued
2023-05-26 08:23:45.797	[warn]	Missing container: other bookmarks
2023-05-26 08:23:45.805	[warn]	Missing container: other bookmarks
2023-05-26 08:24:05.057	[trace]	Waiting for syncs to finish...
2023-05-26 08:24:11.303	[trace]	Waiting for syncs to finish...
2023-05-26 08:24:12.294	[trace]	Cancelling sync
2023-05-26 08:24:12.302	[trace]	Sync zyshrn (cancel) queued
2023-05-26 08:24:12.326	[trace]	Processing sync zyshrn (0 in queue)
2023-05-26 08:24:28.544	[error]		Error: [10006] DailyNewSyncLimitReached at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:1818:38 at chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:140:44 at m.$digest (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:151:185) at m.$apply (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:155:35) at k (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:106:129) at v (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:111:206) at y.onload (chrome-extension://lcbjdhceifofjlpecfpeimnnphbcjgnc/js/app.min.js:112:125)
2023-05-26 08:25:05.567	[trace]	Service url changed to: https://xbrowsersync.freerangecloud.com
2023-05-26 08:25:15.867	[trace]	Sync 1bp8dst (pull) queued
2023-05-26 08:25:15.884	[trace]	Processing sync 1bp8dst (0 in queue)
2023-05-26 08:25:16.403	[warn]	Missing container: other bookmarks
2023-05-26 08:25:16.414	[trace]	Sync 1bp8dst failed
2023-05-26 08:25:16.420	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2023-05-26 08:25:16.426	[trace]	Sync 1teocml (pull) queued
2023-05-26 08:25:16.431	[trace]	Processing sync 1teocml (0 in queue)
2023-05-26 08:25:16.810	[warn]	Missing container: other bookmarks
2023-05-26 08:25:16.817	[trace]	Sync 1teocml failed
2023-05-26 08:25:16.827	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2023-05-26 08:26:37.510	[trace]	Restoring data
2023-05-26 08:26:37.584	[trace]	Service url changed to: https://xbrowsersync.freerangecloud.com
2023-05-26 08:26:37.589	[trace]	Sync 1lff2so (pull) queued
2023-05-26 08:26:37.619	[trace]	Processing sync 1lff2so (0 in queue)
2023-05-26 08:26:37.626	[warn]	Missing container: other bookmarks
2023-05-26 08:26:37.631	[trace]	Sync 1lff2so failed
2023-05-26 08:26:37.636	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2023-05-26 08:26:37.641	[trace]	Sync 1kvxhy5 (pull) queued
2023-05-26 08:26:37.647	[trace]	Processing sync 1kvxhy5 (0 in queue)
2023-05-26 08:26:37.652	[trace]	Sync 1kvxhy5 failed
2023-05-26 08:26:37.657	[error]	bookmarks.sync: [10100] MissingClientData
2023-05-26 08:35:28.673	[trace]	Sync 1eqm39t (pull) queued
2023-05-26 08:35:28.689	[trace]	Processing sync 1eqm39t (0 in queue)
2023-05-26 08:35:29.235	[warn]	Missing container: other bookmarks
2023-05-26 08:35:29.245	[trace]	Sync 1eqm39t failed
2023-05-26 08:35:29.253	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2023-05-26 08:35:29.260	[trace]	Sync 12arweq (pull) queued
2023-05-26 08:35:29.266	[trace]	Processing sync 12arweq (0 in queue)
2023-05-26 08:35:29.641	[warn]	Missing container: other bookmarks
2023-05-26 08:35:29.650	[trace]	Sync 12arweq failed
2023-05-26 08:35:29.658	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2023-05-26 08:35:52.006	[trace]	Optional permissions removed
2023-05-26 08:35:53.460	[trace]	Optional permissions granted
2023-05-26 08:36:12.838	[trace]	Restoring data
2023-05-26 08:36:12.915	[trace]	Service url changed to: https://xbrowsersync.freerangecloud.com
2023-05-26 08:36:12.921	[trace]	Sync nw02i0 (pull) queued
2023-05-26 08:36:12.948	[trace]	Processing sync nw02i0 (0 in queue)
2023-05-26 08:36:12.962	[warn]	Missing container: other bookmarks
2023-05-26 08:36:12.969	[trace]	Sync nw02i0 failed
2023-05-26 08:36:12.976	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2023-05-26 08:36:12.983	[trace]	Sync p6cdgg (pull) queued
2023-05-26 08:36:12.989	[trace]	Processing sync p6cdgg (0 in queue)
2023-05-26 08:36:12.993	[trace]	Sync p6cdgg failed
2023-05-26 08:36:12.999	[error]	bookmarks.sync: [10100] MissingClientData
2023-05-26 08:37:35.820	[trace]	Starting up
2023-05-26 08:37:35.845	[trace]	{"checkForAppUpdates":true,"displayHelp":false,"displayOtherSyncsWarning":false,"displayPermissions":false,"lastUpdated":"2023-05-26T08:23:07.000Z","serviceUrl":"https://xbrowsersync.freerangecloud.com","syncBookmarksToolbar":true,"syncId":"8e732e699d6340ffa22bec7a18920d50","appVersion":"1.5.2","platform":{"name":"chrome","version":"112.0.0","mobile":false,"os":"OS X 10.15.7"}}
2023-05-26 08:42:37.490	[trace]	Restoring data
2023-05-26 08:42:37.567	[trace]	Service url changed to: https://xbrowsersync.freerangecloud.com
2023-05-26 08:42:37.572	[trace]	Sync odod16 (pull) queued
2023-05-26 08:42:37.600	[trace]	Processing sync odod16 (0 in queue)
2023-05-26 08:42:37.606	[warn]	Missing container: other bookmarks
2023-05-26 08:42:37.611	[trace]	Sync odod16 failed
2023-05-26 08:42:37.617	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2023-05-26 08:42:37.621	[trace]	Sync rahkvj (pull) queued
2023-05-26 08:42:37.627	[trace]	Processing sync rahkvj (0 in queue)
2023-05-26 08:42:37.632	[trace]	Sync rahkvj failed
2023-05-26 08:42:37.637	[error]	bookmarks.sync: [10100] MissingClientData
2023-05-26 08:43:02.515	[trace]	Sync 1pmj0fb (pull) queued
2023-05-26 08:43:02.527	[trace]	Processing sync 1pmj0fb (0 in queue)
2023-05-26 08:43:03.059	[warn]	Missing container: other bookmarks
2023-05-26 08:43:03.070	[trace]	Sync 1pmj0fb failed
2023-05-26 08:43:03.077	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks
2023-05-26 08:43:03.083	[trace]	Sync 1fcgywc (pull) queued
2023-05-26 08:43:03.089	[trace]	Processing sync 1fcgywc (0 in queue)
2023-05-26 08:43:03.493	[warn]	Missing container: other bookmarks
2023-05-26 08:43:03.503	[trace]	Sync 1fcgywc failed
2023-05-26 08:43:03.511	[error]	bookmarks.sync: [10104] FailedRemoveLocalBookmarks

**Comment by jdevl32** [comment]
Same experience for me.  Although, I am on Linux Mint Debian 5.  I believe I don't have this issue on Edge with Windows 11 -- I will double check and report back...

**Comment by natpicone** [comment]
MarkSync is now live on both stores, built on Manifest V3:

Chrome Web Store: https://chromewebstore.google.com/detail/marksync/ajmlmhlkkindginlgpgeeelnimadgckl
Firefox Add-ons: https://addons.mozilla.org/firefox/addon/marksync/

Source: https://github.com/MarkSyncOrg
Site: https://marksync.org/

See #534 for the full announcement.
