### ISSUE TITLE
Invalid Credentials Error

### ISSUE THREAD

**Issue by laduko** [xbrowsersync/app#476]
**Describe the issue you are experiencing**

Opened browser (Firefox) & an 'invalid credentials' notification appeared from the xBrowserSync plugin. I entered the correct Sync ID & password, but keep getting the same 'Invalid Credentials' error.

Checked on my Android, opened the XBrowserSync app and saw the same error appear. Cannot login anywhere and cannot backup/view/access the bookmarks saved. 

Service appears to be functioning normally (api.xbrowsersync.org)

**How can the issue be reproduced?**

1. Open XBrowserSync plugin from browser (or Android app)
2. Entered credentials
3. Error: 

> Invalid credentials. Check that your sync ID, password and service URL have been entered correctly

**Desktop browser**

- OS: Win11Pro & OpenSUSE TW
- Browser: Firefox
- Version: 124.0.2 

**Mobile device**

- Device: Samsung S23 Ultra
- OS: Android
- Version: 14

**Application log**
```
2024-02-15 21:16:45.660	[trace]	Starting up
2024-02-15 21:16:45.673	[trace]	{"syncEnabled":true,"syncVersion":"1.5.2","lastUpdated":"2024-01-31T12:43:23.479Z","appVersion":"1.5.2","checkForAppUpdates":true,"serviceUrl":"https://api.xbrowsersync.org","displayHelp":false,"syncId":"8fb98d7037d547ceb6ff4d64681e5331","platform":{"name":"Android","device":"samsung SM-S918B"}}
2024-02-15 21:16:47.400	[trace]	Updates available, local:2024-01-31T12:43:23.479Z remote:2024-02-12T22:24:56.953Z
2024-02-15 21:16:47.407	[trace]	Sync 1kxldvz (pull) queued
2024-02-15 21:16:47.420	[trace]	Processing sync 1kxldvz (0 in queue)
2024-04-15 09:10:13.853	[trace]	Starting up
2024-04-15 09:10:13.865	[trace]	{"syncEnabled":true,"syncVersion":"1.5.2","lastUpdated":"2024-02-12T22:24:56.953Z","appVersion":"1.5.2","checkForAppUpdates":true,"serviceUrl":"https://api.xbrowsersync.org","displayHelp":false,"syncId":"8fb98d7037d547ceb6ff4d64681e5331","platform":{"name":"Android","device":"samsung SM-S918B"}}
2024-04-15 09:10:15.552	[error]		Error: [10106] NoDataFound at file:///android_asset/www/js/app.min.js:2532:42 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onload (file:///android_asset/www/js/app.min.js:112:125)
2024-04-15 09:10:30.968	[error]		Error: [10106] NoDataFound at file:///android_asset/www/js/app.min.js:2507:42 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onload (file:///android_asset/www/js/app.min.js:112:125)
2024-04-15 09:24:59.306	[trace]	Starting up
2024-04-15 09:24:59.316	[trace]	{"syncEnabled":true,"syncVersion":"1.5.2","lastUpdated":"2024-02-12T22:24:56.953Z","appVersion":"1.5.2","checkForAppUpdates":true,"serviceUrl":"https://api.xbrowsersync.org","displayHelp":false,"syncId":"8fb98d7037d547ceb6ff4d64681e5331","platform":{"name":"Android","device":"samsung SM-S918B"}}
2024-04-15 09:25:00.987	[error]		Error: [10106] NoDataFound at file:///android_asset/www/js/app.min.js:2532:42 at file:///android_asset/www/js/app.min.js:140:44 at m.$digest (file:///android_asset/www/js/app.min.js:151:185) at m.$apply (file:///android_asset/www/js/app.min.js:155:35) at k (file:///android_asset/www/js/app.min.js:106:129) at v (file:///android_asset/www/js/app.min.js:111:206) at y.onload (file:///android_asset/www/js/app.min.js:112:125)
```

**Comment by imgustavo** [comment]
Same here

**Comment by wuniversales** [comment]
Same here

**Comment by wuniversales** [comment]
Same here

**Comment by RealFakeGitter** [comment]
No resolutilon? its been years?
